'use client';
import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { authApi } from '@/lib/api-client';
import { Alert } from '@/components/ui';
import AuthShell from '@/components/auth/AuthShell';
import { authErrorMessage } from '@/components/auth/auth-errors';

export default function RegisterClient(){
  const router=useRouter();
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[show,setShow]=useState(false),[verificationEmail,setVerificationEmail]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');try{const r=await authApi.signup(email,password,name);if(r.verificationRequired)setVerificationEmail(email.trim().toLowerCase());else router.replace('/candidate')}catch(cause){setError(authErrorMessage(cause,'register'))}finally{setLoading(false)}}
  return <AuthShell>{verificationEmail?<div className="verification-state"><span className="verification-mark" aria-hidden="true">✓</span><span className="eyebrow">XÁC MINH TÀI KHOẢN</span><h1>Kiểm tra email của bạn</h1><p>Chúng tôi đã gửi liên kết xác minh đến <strong>{verificationEmail}</strong>.</p><Alert tone="success" title="Tạo tài khoản thành công">Nhấn vào liên kết trong email để kích hoạt tài khoản, sau đó đăng nhập và bắt đầu luyện tập.</Alert><p className="verification-help">Chưa thấy email? Hãy kiểm tra thư mục Spam/Thư rác và địa chỉ email bạn đã nhập.</p><Link href="/login" className="primary auth-inline-cta">Đến trang đăng nhập</Link><button type="button" className="verification-back" onClick={()=>setVerificationEmail('')}>Dùng địa chỉ email khác</button></div>:<><span className="eyebrow">BẮT ĐẦU LUYỆN TẬP</span><h1>Tạo tài khoản</h1><p className="auth-subtitle">Lưu tiến độ và xem lại lịch sử luyện tập của bạn.</p>{error&&<Alert tone="danger">{error}</Alert>}<form onSubmit={submit} className="auth-form"><label htmlFor="register-name">Tên hiển thị</label><input id="register-name" value={name} onChange={e=>setName(e.target.value)} maxLength={80} autoComplete="name" disabled={loading}/><label htmlFor="register-email">Email</label><input id="register-email" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required disabled={loading}/><label htmlFor="register-password">Mật khẩu</label><div className="password-field"><input id="register-password" type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} minLength={8} autoComplete="new-password" required disabled={loading}/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?'Ẩn mật khẩu':'Hiện mật khẩu'}>{show?'Ẩn':'Hiện'}</button></div><small className="field-hint">Tối thiểu 8 ký tự.</small><button type="submit" className="primary auth-submit" disabled={loading}>{loading?'Đang tạo tài khoản…':'Tạo tài khoản'}</button></form><div className="auth-links auth-links-centered"><span>Đã có tài khoản? <Link href="/login">Đăng nhập</Link></span></div></>}</AuthShell>;
}
