import {JAPANESE_NATURALNESS_PROMPT_VERSION,JAPANESE_NATURALNESS_SYSTEM_PROMPT_V1,JapaneseNaturalnessError,finalizeJapaneseNaturalnessAssessment,validateJapaneseNaturalnessOutput,type JapaneseNaturalnessAssessment,type JapaneseNaturalnessInput,type JapaneseNaturalnessIssue,type JapaneseNaturalnessIssueCode} from './japanese-naturalness';

export interface JapaneseNaturalnessProvider{name:string;model?:string;judge(input:JapaneseNaturalnessInput):Promise<JapaneseNaturalnessAssessment>}

function issue(code:JapaneseNaturalnessIssueCode,severity:JapaneseNaturalnessIssue['severity'],evidence:string,reason:string):JapaneseNaturalnessIssue{return {code,severity,evidence,reason,suggestedAction:'Revise the affected language and submit it for a new independent naturalness review.'}}
function expectedStyle(input:JapaneseNaturalnessInput){return input.section==='listening'||input.section==='conversation_expression'?'SPOKEN' as const:input.section==='reading'?'WRITTEN' as const:'MIXED' as const}

export class MockJapaneseNaturalnessProvider implements JapaneseNaturalnessProvider{
  name='mock-japanese-naturalness';model='deterministic-language-signals-v1';
  async judge(input:JapaneseNaturalnessInput):Promise<JapaneseNaturalnessAssessment>{
    const body=[input.instruction,input.stem,input.audioScript||''].join('\n');const all=[body,...input.choices].join('\n');const issues:JapaneseNaturalnessIssue[]=[];const choiceCodes=input.choices.map(()=>[] as JapaneseNaturalnessIssueCode[]);const spoken=expectedStyle(input)==='SPOKEN';const written=expectedStyle(input)==='WRITTEN';
    const add=(x:JapaneseNaturalnessIssue)=>{if(!issues.some(current=>current.code===x.code&&current.evidence===x.evidence))issues.push(x)};
    if(/駅で行きます|学校で行きます|病院で行きます|(?:日曜日|月曜日|明日)で[^。\n]*(?:会います|行きます)/.test(all))add(issue('PARTICLE_ERROR','MAJOR',(all.match(/(?:駅|学校|病院)で行きます|(?:日曜日|月曜日|明日)で[^。\n]*(?:会います|行きます)/)||['particle error'])[0],'The particle is incorrect for the destination or time expression in this construction.'));
    if(/薬を食べ|風邪を食べ|写真を聞き/.test(all))add(issue('UNNATURAL_COLLOCATION','MAJOR',(all.match(/薬を食べ\S*|風邪を食べ\S*|写真を聞き\S*/)||['unnatural collocation'])[0],'The noun and verb do not form a natural Japanese collocation.'));
    if(spoken&&/(買い物を実施します|食事を実施します)/.test(body))add(issue('UNNATURAL_WORD_CHOICE','MAJOR',(body.match(/(?:買い物|食事)を実施します/)||['bureaucratic wording'])[0],'The wording is grammatically possible but bureaucratic and unnatural in everyday conversation.'));
    if(spoken&&/(拝啓|敬具|左様でございます|〜するものとする|である。)/.test(body))add(issue('REGISTER_TOO_FORMAL','MAJOR',(body.match(/拝啓|敬具|左様でございます|するものとする|である。/)||['formal expression'])[0],'The expression is bookish or document-like for the declared spoken interaction.'));
    if(spoken&&/(するものとする|である。|なお、)/.test(input.audioScript||''))add(issue('WRITTEN_STYLE_IN_SPOKEN_CONTEXT','MAJOR',(input.audioScript||'').match(/するものとする|である。|なお、/)?.[0]||'written syntax','The listening script uses written syntax that is implausible as everyday speech.'));
    if(written&&/(やばい|だよ[。！]?|してね[。！]?|ないでね[。！]?|持って帰って|じゃん)/.test(body))add(issue('REGISTER_TOO_CASUAL','MAJOR',(body.match(/やばい|だよ|してね|ないでね|持って帰って|じゃん/)||['casual wording'])[0],'The wording is too casual for the declared practical written material.'));
    if(/先生が参ります|社長が参ります|お客様が[^。\n]*(?:拝見|参りました)/.test(all))add(issue('KEIGO_MISUSE','MAJOR',(all.match(/先生が参ります|社長が参ります|お客様が[^。\n]*(?:拝見|参りました)/)||['keigo misuse'])[0],'Humble language is incorrectly applied to a person who should be respected.'));
    if(spoken&&/(承知いたしました[\s\S]*参上いたします|左様でございます[\s\S]*参上いたします)/.test(body))add(issue('SEVERE_REGISTER_MISMATCH','CRITICAL',(body.match(/承知いたしました|左様でございます/)||['severe register mismatch'])[0],'The ceremonial business register is severely implausible in the declared everyday conversation.'));
    if(/A[:：][\s\S]*(?:元気|何時)[\s\S]*[\n\r]+B[:：][\s\S]*(?:三時|元気|買いました)/.test(body)&&((/元気/.test(body)&&/三時/.test(body))||(/何時/.test(body)&&/買いました/.test(body))))add(issue('ARTIFICIAL_DIALOGUE_FLOW','MAJOR','The response does not answer the preceding turn.','The turns are grammatical in isolation but pragmatically disconnected.'));
    input.choices.forEach((choice,index)=>{if(/食べるを|をです|にを|をを|ますでした|[一二三四五六七八九十0-9]+時ます|時を開き|時でする/.test(choice)){choiceCodes[index].push('LANGUAGE_ERROR_LEAKS_CORRECT_ANSWER');add(issue('LANGUAGE_ERROR_LEAKS_CORRECT_ANSWER','CRITICAL',choice,'A malformed option supplies a grammatical clue and compromises the assessment.'));}});
    if(/私がは|をを|にを/.test(body))add(issue('BROKEN_JAPANESE','CRITICAL',(body.match(/私がは|をを|にを/)||['broken construction'])[0],'The construction is grammatically broken and cannot be accepted as natural Japanese.'));
    if(/するをします|食べるをします/.test(body))add(issue('MEANING_CORRUPTED_BY_LANGUAGE_ERROR','CRITICAL',(body.match(/するをします|食べるをします/)||['corrupted construction'])[0],'The language error corrupts the intended meaning.'));
    const deductions={grammar:0,naturalness:0,collocation:0,register:0,contextFit:0,spokenWrittenFit:0,conversationFlow:0};
    for(const x of issues){const n=x.severity==='CRITICAL'?12:x.severity==='MAJOR'?7:x.severity==='WARNING'?2:0;if(['GRAMMAR_ERROR','BROKEN_JAPANESE','MEANING_CORRUPTED_BY_LANGUAGE_ERROR','PARTICLE_ERROR','PARTICLE_UNNATURAL','LANGUAGE_ERROR_LEAKS_CORRECT_ANSWER'].includes(x.code))deductions.grammar+=n;if(['UNNATURAL_COLLOCATION','UNNATURAL_WORD_CHOICE'].includes(x.code))deductions.collocation+=n;if(['REGISTER_TOO_FORMAL','REGISTER_TOO_CASUAL','POLITENESS_MISMATCH','KEIGO_MISUSE','SEVERE_REGISTER_MISMATCH'].includes(x.code))deductions.register+=n;if(['WRITTEN_STYLE_IN_SPOKEN_CONTEXT','SPOKEN_STYLE_IN_WRITTEN_CONTEXT'].includes(x.code))deductions.spokenWrittenFit+=n;if(['ARTIFICIAL_DIALOGUE_FLOW','UNINTELLIGIBLE_DIALOGUE'].includes(x.code))deductions.conversationFlow+=n;deductions.naturalness+=Math.ceil(n/2);deductions.contextFit+=Math.ceil(n/3);}
    const scores={grammar:Math.max(0,20-deductions.grammar),naturalness:Math.max(0,20-deductions.naturalness),collocation:Math.max(0,15-deductions.collocation),register:Math.max(0,15-deductions.register),contextFit:Math.max(0,10-deductions.contextFit),spokenWrittenFit:Math.max(0,10-deductions.spokenWrittenFit),conversationFlow:Math.max(0,10-deductions.conversationFlow),overall:0};scores.overall=scores.grammar+scores.naturalness+scores.collocation+scores.register+scores.contextFit+scores.spokenWrittenFit+scores.conversationFlow;
    const actualStyle=issues.some(x=>x.code==='WRITTEN_STYLE_IN_SPOKEN_CONTEXT')?'WRITTEN':issues.some(x=>x.code==='REGISTER_TOO_CASUAL')&&written?'SPOKEN':expectedStyle(input);
    const result=finalizeJapaneseNaturalnessAssessment({qaVersion:JAPANESE_NATURALNESS_PROMPT_VERSION,questionId:input.questionId,confidence:'HIGH',scores,contextAssessment:{declaredContext:input.declaredContext,actualStyle,fit:issues.length===0?'GOOD':issues.some(x=>x.severity==='CRITICAL')?'POOR':'ACCEPTABLE'},choiceLanguageAnalysis:input.choices.map((_,index)=>({index,natural:choiceCodes[index].length===0,issues:choiceCodes[index]})),issues});
    return validateJapaneseNaturalnessOutput(result,input);
  }
}

export class HttpJapaneseNaturalnessProvider implements JapaneseNaturalnessProvider{
  name='http-japanese-naturalness';model=process.env.JAPANESE_NATURALNESS_MODEL||process.env.AI_QA_MODEL||'external';
  async judge(input:JapaneseNaturalnessInput):Promise<JapaneseNaturalnessAssessment>{
    const endpoint=process.env.JAPANESE_NATURALNESS_ENDPOINT||process.env.AI_QA_ENDPOINT;if(!endpoint)throw new JapaneseNaturalnessError('JAPANESE_NATURALNESS_PROVIDER_FAILURE','JAPANESE_NATURALNESS_ENDPOINT or AI_QA_ENDPOINT is required.');
    let response:Response;try{response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',...(process.env.JAPANESE_NATURALNESS_API_KEY||process.env.AI_QA_API_KEY?{authorization:`Bearer ${process.env.JAPANESE_NATURALNESS_API_KEY||process.env.AI_QA_API_KEY}`}:{})},body:JSON.stringify({task:'jft_japanese_naturalness',promptVersion:JAPANESE_NATURALNESS_PROMPT_VERSION,systemInstruction:JAPANESE_NATURALNESS_SYSTEM_PROMPT_V1,input})});}catch(error){throw new JapaneseNaturalnessError('JAPANESE_NATURALNESS_PROVIDER_FAILURE',error instanceof Error?error.message:String(error));}
    if(!response.ok)throw new JapaneseNaturalnessError('JAPANESE_NATURALNESS_PROVIDER_FAILURE',`Japanese Naturalness provider failed: ${response.status}`);let json:unknown;try{json=await response.json()}catch{throw new JapaneseNaturalnessError('JAPANESE_NATURALNESS_INVALID_OUTPUT','Japanese Naturalness response is not valid JSON.')};return validateJapaneseNaturalnessOutput(json,input);
  }
}

export function getJapaneseNaturalnessProvider():JapaneseNaturalnessProvider{return process.env.JAPANESE_NATURALNESS_PROVIDER==='http'?new HttpJapaneseNaturalnessProvider():new MockJapaneseNaturalnessProvider()}
