import {ORIGINALITY_DUPLICATE_PROMPT_VERSION,type OriginalityDuplicateAnalysis,type OriginalityDuplicateInput,type OriginalityRelationshipAnalysis} from './originality-duplicate';

export interface OriginalityDuplicateProvider {name:string;model?:string;analyze(input:OriginalityDuplicateInput):Promise<unknown>}

function classify(item:OriginalityDuplicateInput['comparisons'][number]):OriginalityRelationshipAnalysis{
  const score=Math.max(item.ngramSimilarity,item.patternSimilarity,item.containmentSimilarity);const high=item.exactNormalized||item.ngramSimilarity>=.88||item.patternSimilarity>=.94||(item.containmentSimilarity>=.94&&item.ngramSimilarity>=.5);const medium=!high&&(item.ngramSimilarity>=.72||item.patternSimilarity>=.82||(item.containmentSimilarity>=.86&&item.ngramSimilarity>=.3));
  return {comparisonId:item.id,kind:item.kind,semanticRisk:high?'HIGH':medium?'MEDIUM':score>=.55?'LOW':'NONE',relationship:high?(item.kind==='SOURCE'?'SOURCE_COPY':'NEAR_DUPLICATE'):medium?'NEAR_DUPLICATE':score>=.45?'SHARED_KNOWLEDGE':'DISTINCT',evidence:high?'Deterministic lexical and structural evidence indicates reproduction of the same wording or decision pattern.':medium?'Substantial surface or structural overlap requires human comparison.':score>=.45?'Overlap appears limited to shared knowledge or topic language.':'The candidate presents a distinct wording and assessment decision.'};
}
export class MockOriginalityDuplicateProvider implements OriginalityDuplicateProvider {name='mock';model='deterministic-originality-v1';async analyze(input:OriginalityDuplicateInput):Promise<OriginalityDuplicateAnalysis>{return {qaVersion:ORIGINALITY_DUPLICATE_PROMPT_VERSION,questionId:input.questionId,confidence:'HIGH',relationships:input.comparisons.map(classify)}}}

const SYSTEM_PROMPT=`You are QA7, an independent originality and duplicate relationship judge for Japanese practice questions. You never generate, edit, or fix questions. Classify every supplied comparison before any release policy is applied.

Return JSON only with exactly: {"qaVersion":"JFT_ORIGINALITY_DUPLICATE_V1","questionId":"...","confidence":"HIGH|MEDIUM|LOW","relationships":[{"comparisonId":"...","kind":"SOURCE|BATCH|BANK","semanticRisk":"NONE|LOW|MEDIUM|HIGH","relationship":"DISTINCT|SHARED_KNOWLEDGE|NEAR_DUPLICATE|SOURCE_COPY","evidence":"..."}]}.

Use SOURCE_COPY only when source wording, passage, exercise structure, or answer-choice structure is reproduced rather than knowledge abstracted. Use NEAR_DUPLICATE when the same situation, learner decision and answer pattern remain after superficial name, number, date or object changes. Shared vocabulary, grammar, topic, or Can-do alone is not duplication. Analyze every comparison exactly once. Do not output a verdict, score, answer key, explanation, replacement question, or fields outside the contract.`;
export class HttpOriginalityDuplicateProvider implements OriginalityDuplicateProvider {name='http';model=process.env.ORIGINALITY_DUPLICATE_MODEL||'independent-originality-judge';async analyze(input:OriginalityDuplicateInput){const endpoint=process.env.ORIGINALITY_DUPLICATE_ENDPOINT,apiKey=process.env.ORIGINALITY_DUPLICATE_API_KEY;if(!endpoint||!apiKey)throw new Error('ORIGINALITY_DUPLICATE provider is not configured');const response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:this.model,promptVersion:ORIGINALITY_DUPLICATE_PROMPT_VERSION,systemPrompt:SYSTEM_PROMPT,input})});if(!response.ok)throw new Error(`Originality provider failed (${response.status})`);return response.json()}}
export function getOriginalityDuplicateProvider():OriginalityDuplicateProvider{return process.env.ORIGINALITY_DUPLICATE_PROVIDER==='http'?new HttpOriginalityDuplicateProvider():new MockOriginalityDuplicateProvider()}
