import { assertKnowledgeUnit, KnowledgeExtractionResult, PlanningInput, QuestionPlanningResult, SourceExtractionInput, SOURCE_EXTRACTION_PROMPT_V1, QUESTION_PLANNER_PROMPT_V1, SourceFactoryError } from './source-domain';
import type { SectionId } from '@/lib/types';
export interface SourceKnowledgeProvider { name:string;model?:string;extract(input:SourceExtractionInput):Promise<KnowledgeExtractionResult>; }
export interface QuestionPlanningProvider { name:string;model?:string;plan(input:PlanningInput):Promise<QuestionPlanningResult>; }
async function fetchJson(url:string,body:unknown,apiKey:string|undefined,timeoutMs=30000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json',...(apiKey?{authorization:`Bearer ${apiKey}`}:{})},body:JSON.stringify(body),signal:controller.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json();}catch(e){throw new SourceFactoryError('EXTRACTION_FAILED',e instanceof Error?e.message:String(e));}finally{clearTimeout(timer);}}
export class MockSourceKnowledgeProvider implements SourceKnowledgeProvider {name='mock';model='deterministic-source-v1';async extract(input:SourceExtractionInput){const units=input.chunks.slice(0,input.maxKnowledgeUnits).map(c=>({sourceChunkIds:[c.id],chapter:c.chapter,topic:(c.normalizedText.match(/[\u3040-\u30ff\u3400-\u9fff]{2,12}/)?.[0]||input.document.title).slice(0,30),situation:input.document.title,level:'A1' as const,canDo:`Can understand and act in a ${input.document.title} situation.`,grammar:[],vocabulary:Array.from(new Set(c.normalizedText.match(/[\u3040-\u30ff\u3400-\u9fff]{2,10}/g)||[])).slice(0,8),kanji:Array.from(new Set(c.normalizedText.match(/[\u3400-\u9fff]/g)||[])).slice(0,12),expressions:[],keyKnowledge:[c.normalizedText.slice(0,160)],skills:['vocabulary','conversation','reading'] as const,notes:'Review this deterministic extraction before approval.',confidence:.72}));return {units:units.map(x=>({...x,skills:[...x.skills]})),provider:this.name,model:this.model,promptVersion:SOURCE_EXTRACTION_PROMPT_V1};}}
export class HttpSourceKnowledgeProvider implements SourceKnowledgeProvider {name='http';model=process.env.SOURCE_AI_MODEL||'external';async extract(input:SourceExtractionInput){if(!process.env.SOURCE_AI_ENDPOINT)throw new SourceFactoryError('EXTRACTION_FAILED','SOURCE_AI_ENDPOINT is required.');const json=await fetchJson(process.env.SOURCE_AI_ENDPOINT,{task:'extract_source_knowledge',promptVersion:SOURCE_EXTRACTION_PROMPT_V1,input},process.env.SOURCE_AI_API_KEY) as any;if(!Array.isArray(json.units))throw new SourceFactoryError('INVALID_MODEL_OUTPUT','Source provider response must contain units[].');json.units.forEach(assertKnowledgeUnit);return {units:json.units.slice(0,input.maxKnowledgeUnits),provider:this.name,model:this.model,promptVersion:SOURCE_EXTRACTION_PROMPT_V1};}}
export class MockQuestionPlanningProvider implements QuestionPlanningProvider {name='mock';model='deterministic-planner-v1';async plan(input:PlanningInput){const sections:SectionId[]=['script_vocabulary','conversation_expression','listening','reading'];const categories:Record<SectionId,string>={script_vocabulary:'word_usage',conversation_expression:'expression',listening:'conversation',reading:'information_search'};const items=Array.from({length:input.requestedCount},(_,i)=>{const u=input.units[i%input.units.length],section=sections[i%sections.length];return {knowledgeUnitId:u.id,section,category:categories[section],level:u.level,topic:u.topic,canDo:u.canDo,difficulty:'balanced' as const,objective:`Create an original scenario testing ${u.keyKnowledge[i%Math.max(1,u.keyKnowledge.length)]||u.canDo}`,count:1};});return {items,provider:this.name,model:this.model,promptVersion:QUESTION_PLANNER_PROMPT_V1};}}
export class HttpQuestionPlanningProvider implements QuestionPlanningProvider {name='http';model=process.env.SOURCE_AI_MODEL||'external';async plan(input:PlanningInput){if(!process.env.SOURCE_AI_ENDPOINT)throw new SourceFactoryError('PLAN_FAILED','SOURCE_AI_ENDPOINT is required.');const json=await fetchJson(process.env.SOURCE_AI_ENDPOINT,{task:'plan_jft_questions',promptVersion:QUESTION_PLANNER_PROMPT_V1,input},process.env.SOURCE_AI_API_KEY) as any;if(!Array.isArray(json.items))throw new SourceFactoryError('INVALID_MODEL_OUTPUT','Planning provider response must contain items[].');return {items:json.items.slice(0,input.requestedCount),provider:this.name,model:this.model,promptVersion:QUESTION_PLANNER_PROMPT_V1};}}
export const getSourceKnowledgeProvider=():SourceKnowledgeProvider=>process.env.SOURCE_AI_PROVIDER==='http'?new HttpSourceKnowledgeProvider():new MockSourceKnowledgeProvider();
export const getQuestionPlanningProvider=():QuestionPlanningProvider=>process.env.SOURCE_AI_PROVIDER==='http'?new HttpQuestionPlanningProvider():new MockQuestionPlanningProvider();
