import {readFile} from 'node:fs/promises';
import {describe,expect,it} from 'vitest';
import {A1_MACHINE_PIPELINE_VERSION,MACHINE_ACCEPTANCE_THRESHOLD} from '../lib/server/machine-acceptance-contract';

const read=async(path:string)=>JSON.parse(await readFile(path,'utf8')) as any;

describe('A1 Fresh 800 zero-human machine bank',()=>{
  it('partitions every input into exactly one terminal machine state',async()=>{const evidence=await read('data/qa/a1-fresh-800-machine-evidence.json');const accepted=await read('data/production/a1-fresh-800-machine-accepted-v1.json');const rejected=await read('data/reviews/a1-fresh-800-auto-rejected-v1.json');expect(evidence.total).toBe(800);expect(accepted.itemCount+rejected.itemCount).toBe(800);expect(new Set(evidence.records.map((row:any)=>row.id)).size).toBe(800);expect(new Set(evidence.records.map((row:any)=>row.finalDecision))).toEqual(new Set(['MACHINE_ACCEPTED','AUTO_REJECTED']));expect(accepted.items.every((item:any)=>item.status==='MACHINE_ACCEPTED'&&item.approvalMode==='MACHINE'&&!('humanReviewStatus' in item))).toBe(true);expect(rejected.items.every((row:any)=>row.finalDecision==='AUTO_REJECTED'&&row.candidate.status==='AUTO_REJECTED'&&!('humanReviewStatus' in row.candidate))).toBe(true)});
  it('keeps every accepted item above threshold with every hard gate and both judges passing',async()=>{const evidence=await read('data/qa/a1-fresh-800-machine-evidence.json');const rows=evidence.records.filter((row:any)=>row.finalDecision==='MACHINE_ACCEPTED');expect(rows.length).toBeGreaterThan(0);for(const row of rows){expect(row.pipelineVersion).toBe(A1_MACHINE_PIPELINE_VERSION);expect(row.machineConfidence).toBeGreaterThanOrEqual(MACHINE_ACCEPTANCE_THRESHOLD);expect(['deterministicChecks','QA1','QA2','QA3','QA4','QA5','QA6','QA7'].every(key=>row[key].status==='PASS')).toBe(true);expect(row.semanticJudgeA.status).toBe('PASS');expect(row.adversarialJudgeB.status).toBe('PASS');expect(row.adversarialJudgeB.defensibleAlternativeIndexes).toEqual([])}});
  it('uses reloaded, hash-verified machine catalog grounding rather than human approval',async()=>{const grounding=await read('data/production/a1-fresh-800-machine-grounding-evidence-v1.json');expect(grounding.recordCount).toBe(16);expect(new Set(grounding.records.map((row:any)=>row.knowledgeUnitId)).size).toBe(16);for(const row of grounding.records){expect(row.approvalMode).toBe('MACHINE');expect(row.status).toBe('MACHINE_APPROVED_CATALOG_EVIDENCE');expect(row.contentHash).toMatch(/^[a-f0-9]{64}$/);expect(row.sourceFileHash).toMatch(/^[a-f0-9]{64}$/);expect(row.sourceCurriculumReference).toMatch(/\.docx$/)}});
});
