import {afterEach,describe,expect,it,vi} from 'vitest';
import type {QuestionRecord} from '@/lib/admin-types';
import type {FactoryCandidate} from '@/lib/server/factory-domain';
import {ANSWER_ORACLE_PROMPT_VERSION,AnswerOracleError,buildAnswerOracleInput,compareOracleWithDeclaredAnswer,validateAnswerOracleOutput,type AnswerOracleInput,type AnswerOracleSolveResult} from '@/lib/server/answer-oracle';
import {HttpAnswerOracleProvider,type AnswerOracleProvider} from '@/lib/server/answer-oracle-provider';
import {runAnswerOracleGate} from '@/lib/server/factory-service';

const now='2026-08-18T00:00:00.000Z';
function question(overrides:Partial<QuestionRecord>={}):QuestionRecord{return {id:'QA2-1',section:'reading',type:'choice',level:'A1',instruction:'文を読んで答えてください。',prompt:'店は9時に開きます。店は何時に開きますか。',choices:['8時','9時','10時','11時'],answer:1,explanationVi:'9 giờ.',tags:['shop'],version:1,status:'review',source:'ai',createdAt:now,updatedAt:now,...overrides}}
function solve(input:AnswerOracleInput,derived=[1],confidence=.97,extra:Partial<AnswerOracleSolveResult>={}):AnswerOracleSolveResult{return {qaVersion:ANSWER_ORACLE_PROMPT_VERSION,questionId:input.questionId,derivedCorrectOptions:derived,numberOfDefensibleAnswers:derived.length,confidence,choiceAnalysis:input.choices.map((_,index)=>({index,classification:derived.includes(index)?'CORRECT':'PLAUSIBLE_BUT_INCORRECT',reason:derived.includes(index)?'Supported by visible evidence.':'Not supported by visible evidence.'})),ambiguity:{detected:derived.length>1,reason:derived.length>1?'Two choices are defensible.':null},hiddenContextRequired:false,solverNotes:'Independent solve.',...extra};}
class StubProvider implements AnswerOracleProvider{constructor(private result:(input:AnswerOracleInput)=>AnswerOracleSolveResult|Promise<AnswerOracleSolveResult>){ }name='stub';model='test';async solve(input:AnswerOracleInput){return this.result(input)}}
function candidate(q=question()):FactoryCandidate{return {id:'candidate',question:q,qa:{passed:true,score:96,issues:[]},generation:{provider:'generator',promptVersion:'generator-v1',createdAt:now},contentQa:{qaVersion:'JFT_CONTENT_QA_V1',questionId:q.id,verdict:'PASS',hardFail:false,confidence:'HIGH',independentAnswer:{derivedCorrectOption:1,declaredCorrectOption:1,match:true},classification:{declaredLevel:'A1',estimatedLevel:'A1',levelMatch:'MATCH',declaredSection:'READING',actualSection:'READING',declaredCategory:'CONTENT_COMPREHENSION',actualCategory:'CONTENT_COMPREHENSION',targetCanDo:'',actualCanDo:''},curriculum:{grounded:true,knowledgeUnitIds:[],requiredVocabulary:[],requiredKanji:[],requiredGrammar:[],requiredExpressions:[],outsideKnowledge:[]},choiceAnalysis:[],scores:{japaneseNaturalness:20,canDoAlignment:15,situationRealism:15,answerUniqueness:15,distractorQuality:10,levelAppropriateness:10,categoryAlignment:5,originality:5,metadataCompleteness:5,total:100},originality:{sourceCopyRisk:'NONE',duplicateRisk:'NONE'},assessmentValue:'HIGH',issues:[],release:{eligibleForQuestionBank:true,requiresHumanReview:false,blockReason:[]}}}}

describe('QA2 deterministic comparison',()=>{
  it('passes one high-confidence matching answer',()=>{const input=buildAnswerOracleInput(question());expect(compareOracleWithDeclaredAnswer(solve(input),1,{provider:'test'}).outcome).toBe('ORACLE_MATCH')});
  it('hard-fails an objectively different answer key',()=>{const input=buildAnswerOracleInput(question({answer:1}));const gate=compareOracleWithDeclaredAnswer(solve(input,[2]),1,{provider:'test'});expect(gate).toMatchObject({verdict:'FAIL',hardFail:true,outcome:'ANSWER_KEY_MISMATCH'})});
  it('hard-fails two semantically defensible answers',()=>{const input=buildAnswerOracleInput(question({choices:['9時','午前9時','10時','11時']}));expect(compareOracleWithDeclaredAnswer(solve(input,[0,1]),0,{provider:'test'}).outcome).toBe('MULTIPLE_DEFENSIBLE_ANSWERS')});
  it('hard-fails when no option is supported by the passage',()=>{const input=buildAnswerOracleInput(question());expect(compareOracleWithDeclaredAnswer(solve(input,[]),1,{provider:'test'}).outcome).toBe('NO_DEFENSIBLE_ANSWER')});
  it('reviews rather than passes below the simulator threshold',()=>{const input=buildAnswerOracleInput(question());expect(compareOracleWithDeclaredAnswer(solve(input,[1],.84),1,{provider:'test',threshold:.85}).verdict).toBe('REVIEW')});
  it('hard-fails hidden learner context',()=>{const input=buildAnswerOracleInput(question({prompt:'この写真の人は何をしていますか。'}));const gate=compareOracleWithDeclaredAnswer(solve(input,[1],.97,{hiddenContextRequired:true}),1,{provider:'test'});expect(gate.outcome).toBe('HIDDEN_CONTEXT_REQUIRED')});
});

describe('QA2 input boundary and validation',()=>{
  it('blinds answer key, explanation, QA1 evidence and generator reasoning',()=>{const q=question({answer:3,explanationVi:'SECRET_EXPLANATION'});const input=buildAnswerOracleInput(q);expect(input).not.toHaveProperty('answer');expect(input).not.toHaveProperty('answerKey');expect(input).not.toHaveProperty('explanationVi');expect(JSON.stringify(input)).not.toContain('SECRET_EXPLANATION')});
  it('uses full learner-visible grammar construction and reading passage',()=>{const grammar=buildAnswerOracleInput(question({section:'conversation_expression',instruction:'文を完成してください。',prompt:'きのう、先生に（　）。',choices:['聞きました','聞きます','聞いて','聞く']}));expect(`${grammar.stem}${grammar.choices[0]}`).toContain('きのう、先生に（　）。聞きました');expect(buildAnswerOracleInput(question()).stem).toContain('店は9時')});
  it('includes listening script only for semantic QA',()=>{const input=buildAnswerOracleInput(question({section:'listening',type:'audio_choice',prompt:'男の人は何時に来ますか。'}),'男の人は9時に来ます。');expect(input.audioScript).toContain('9時');expect(input).not.toHaveProperty('audioSrc')});
  it('rejects invalid provider output instead of coercing it',()=>{const input=buildAnswerOracleInput(question());expect(()=>validateAnswerOracleOutput({...solve(input),confidence:'0.97'},input)).toThrow(AnswerOracleError)});
});

describe('QA2 provider and pipeline integration',()=>{
  afterEach(()=>{vi.unstubAllGlobals();delete process.env.ANSWER_ORACLE_ENDPOINT});
  it('sends an answer-blinded HTTP payload',async()=>{process.env.ANSWER_ORACLE_ENDPOINT='https://oracle.test';let body:any;vi.stubGlobal('fetch',vi.fn(async(_url,_init)=>{body=JSON.parse(String((_init as RequestInit).body));return new Response(JSON.stringify(solve(body.input)),{status:200,headers:{'content-type':'application/json'}})}));await new HttpAnswerOracleProvider().solve(buildAnswerOracleInput(question({answer:3})));expect(body.input).not.toHaveProperty('answer');expect(body.input).not.toHaveProperty('answerKey');expect(body).not.toHaveProperty('declaredAnswerKey')});
  it('turns invalid JSON and provider failure into non-passing REVIEW evidence',async()=>{const c1=candidate();await runAnswerOracleGate(c1,new StubProvider(async()=>{throw new AnswerOracleError('QA_ORACLE_INVALID_OUTPUT','bad')}));expect(c1.answerOracleQa).toMatchObject({verdict:'REVIEW',outcome:'QA_ORACLE_INVALID_OUTPUT'});const c2=candidate();await runAnswerOracleGate(c2,new StubProvider(async()=>{throw new Error('offline')}));expect(c2.answerOracleQa).toMatchObject({verdict:'REVIEW',outcome:'QA_ORACLE_PROVIDER_FAILURE'})});
  it('lets QA2 failure override an existing QA1 PASS',async()=>{const c=candidate();await runAnswerOracleGate(c,new StubProvider(input=>solve(input,[2])));expect(c.contentQa?.verdict).toBe('PASS');expect(c.answerOracleQa?.verdict).toBe('FAIL');expect(c.qa.passed).toBe(false);expect(c.qa.issues.some(x=>x.code==='answer_oracle_fail')).toBe(true)});
  it('supports independent listening semantic derivation',async()=>{const q=question({section:'listening',type:'audio_choice',answer:1,prompt:'何時ですか。'}),c=candidate(q);c.audioScript='9時です。';await runAnswerOracleGate(c,new StubProvider(input=>{expect(input.audioScript).toBe('9時です。');return solve(input,[1])}));expect(c.answerOracleQa?.verdict).toBe('PASS')});
});
