import {afterEach,describe,expect,it,vi} from 'vitest';
import type {QuestionRecord} from '@/lib/admin-types';
import type {FactoryCandidate,FactoryJob} from '@/lib/server/factory-domain';
import type {KnowledgeUnit} from '@/lib/server/source-domain';
import {CURRICULUM_GROUNDING_PROMPT_VERSION,CurriculumGroundingError,finalizeCurriculumGrounding,validateCurriculumGroundingAnalysis,type ApprovedKnowledgeUnitEvidence,type CurriculumGroundingAnalysis,type CurriculumGroundingInput,type CurriculumKnowledgeAnalysisItem} from '@/lib/server/curriculum-grounding';
import {HttpCurriculumGroundingProvider,MockCurriculumGroundingProvider,type CurriculumGroundingProvider} from '@/lib/server/curriculum-grounding-provider';
import {selectCurriculumUnits,type CurriculumCatalog} from '@/lib/server/curriculum-retrieval';
import {runCurriculumGroundingGate} from '@/lib/server/factory-service';

const now='2026-08-18T00:00:00.000Z';
function unit(overrides:Partial<ApprovedKnowledgeUnitEvidence>={}):ApprovedKnowledgeUnitEvidence{return {id:'KU-BASIC',sourceDocumentId:'SRC-1',sourceChunkIds:['SC-1'],status:'approved',topic:'日常生活',situation:'店',level:'A1',canDo:'簡単な店の情報を理解できる',grammar:['～ます','～ません'],vocabulary:['店','りんご','会議','時','閉まる'],kanji:['店','会議','時'],expressions:['これはいくらですか'],keyKnowledge:['店の時間と値段を理解する'],skills:['vocabulary','reading','listening'],...overrides}}
function retrieval(overrides:Partial<CurriculumGroundingInput['retrieval']>={}):CurriculumGroundingInput['retrieval']{return {complete:true,strategy:'FULL_APPROVED_CATALOG',totalApprovedUnits:1,returnedUnitCount:1,searchedSourceDocumentIds:['SRC-1'],intendedKnowledgeUnitIds:['KU-BASIC'],missingIntendedKnowledgeUnitIds:[],...overrides}}
function input(overrides:Partial<CurriculumGroundingInput>={}):CurriculumGroundingInput{const approved=overrides.approvedKnowledgeUnits||[unit()];return {questionId:'QA4-1',instruction:'文を読んで答えてください。',stem:'店は午後6時に閉まります。店は何時に閉まりますか。',choices:['5時','6時','7時','8時'],section:'reading',targetLevel:'A1',targetCanDo:'店の時間を理解できる',topic:'店',approvedKnowledgeUnits:approved,sourceChunks:[{id:'SC-1',sourceDocumentId:'SRC-1',normalizedText:'店の時間と値段'}],retrieval:retrieval({totalApprovedUnits:approved.length,returnedUnitCount:approved.length}),...overrides}}
function item(overrides:Partial<CurriculumKnowledgeAnalysisItem>={}):CurriculumKnowledgeAnalysisItem{return {type:'VOCABULARY',value:'店',role:'REQUIRED',source:'PASSAGE',support:'SUPPORTED',knowledgeUnitIds:['KU-BASIC'],sourceChunkIds:['SC-1'],evidence:'KU-BASIC teaches 店.',reason:'The learner must understand 店 to locate the requested time.',contradictedByCurriculum:false,...overrides}}
function analysis(items:CurriculumKnowledgeAnalysisItem[],confidence:CurriculumGroundingAnalysis['confidence']='HIGH',questionId='QA4-1'):CurriculumGroundingAnalysis{return {qaVersion:CURRICULUM_GROUNDING_PROMPT_VERSION,questionId,confidence,knowledgeAnalysis:items}}
function normalized(items:CurriculumKnowledgeAnalysisItem[],overrides:Partial<CurriculumGroundingInput>={},confidence:CurriculumGroundingAnalysis['confidence']='HIGH'){const value=input(overrides);return finalizeCurriculumGrounding(analysis(items,confidence,value.questionId),value)}
function question(overrides:Partial<QuestionRecord>={}):QuestionRecord{return {id:'QA4-1',section:'reading',type:'choice',level:'A1',instruction:'読んでください。',prompt:'店は6時に閉まります。何時に閉まりますか。',choices:['5時','6時','7時','8時'],answer:1,explanationVi:'6 giờ.',tags:[],version:1,status:'review',source:'ai',createdAt:now,updatedAt:now,...overrides}}
function candidate(q=question()):FactoryCandidate{return {id:'C-1',question:q,qa:{passed:true,score:98,issues:[]},generation:{provider:'generator',promptVersion:'v1',createdAt:now},contentQa:{verdict:'PASS'} as any,answerOracleQa:{verdict:'PASS'} as any,japaneseNaturalnessQa:{verdict:'PASS'} as any}}
class StubProvider implements CurriculumGroundingProvider{constructor(private fn:(input:CurriculumGroundingInput)=>CurriculumGroundingAnalysis|Promise<CurriculumGroundingAnalysis>){}name='stub-curriculum';model='test';evaluate(value:CurriculumGroundingInput){return Promise.resolve(this.fn(value))}}

describe('QA4 deterministic curriculum policy',()=>{
  it('passes when every required item is supported with provenance',()=>{const result=normalized([item(),item({type:'GRAMMAR',value:'～ます'}),item({type:'EXPRESSION',value:'これはいくらですか'})]);expect(result).toMatchObject({verdict:'PASS',hardFail:false,coverage:{requiredCount:3,supportedCount:3,coverageRatio:1},provenance:{complete:true}})});
  it('hard-fails unsupported required grammar even at high aggregate coverage',()=>{const items=Array.from({length:19},(_,i)=>item({value:`店${i}`}));items.push(item({type:'GRAMMAR',value:'～ざるを得ない',support:'UNSUPPORTED',knowledgeUnitIds:[],sourceChunkIds:[],evidence:'No approved grammar support.',reason:'Required to understand obligation.'}));const result=normalized(items);expect(result.coverage.coverageRatio).toBe(.95);expect(result).toMatchObject({verdict:'FAIL',hardFail:true});expect(result.issues.map(x=>x.code)).toContain('REQUIRED_GRAMMAR_UNSUPPORTED')});
  it.each([['VOCABULARY','受付','REQUIRED_VOCABULARY_UNSUPPORTED'],['KANJI','受付','REQUIRED_KANJI_UNSUPPORTED'],['EXPRESSION','～てもいいですか','REQUIRED_EXPRESSION_UNSUPPORTED']] as const)('hard-fails unsupported required %s', (type,value,code)=>{const result=normalized([item({type,value,support:'UNSUPPORTED',knowledgeUnitIds:[],sourceChunkIds:[],evidence:'No approved support.',reason:'Essential to solve.'})]);expect(result.issues.map(x=>x.code)).toContain(code);expect(result.hardFail).toBe(true)});
  it('does not require kanji knowledge when furigana removes that requirement',()=>{const result=normalized([item({value:'うけつけ'}),item({type:'KANJI',value:'受付',role:'INCIDENTAL',support:'UNSUPPORTED',knowledgeUnitIds:[],sourceChunkIds:[],evidence:'受付（うけつけ） supplies the reading.',reason:'Kanji recognition is not needed to answer the location question.'})],{approvedKnowledgeUnits:[unit({vocabulary:[...unit().vocabulary,'うけつけ']})]});expect(result.verdict).toBe('PASS')});
  it('allows a new person name because it is incidental',()=>{const result=normalized([item(),item({type:'OTHER',value:'田中さん',role:'INCIDENTAL',source:'STEM',support:'UNSUPPORTED',knowledgeUnitIds:[],sourceChunkIds:[],evidence:'New proper name.',reason:'The identity does not determine the answer.'})]);expect(result.verdict).toBe('PASS');expect(result.coverage.requiredCount).toBe(1)});
  it('allows novel numbers and dates when they are incidental',()=>{const result=normalized([item(),item({type:'OTHER',value:'8月19日・650円',role:'INCIDENTAL',support:'UNSUPPORTED',knowledgeUnitIds:[],sourceChunkIds:[],evidence:'Surface fact.',reason:'The exact date and price are supplied.'})]);expect(result.verdict).toBe('PASS')});
  it('does not fail an irrelevant unknown word',()=>{const result=normalized([item(),item({type:'VOCABULARY',value:'ドラゴンフルーツ',role:'INCIDENTAL',support:'UNSUPPORTED',knowledgeUnitIds:[],sourceChunkIds:[],evidence:'Irrelevant context.',reason:'The question asks about りんご.'})]);expect(result.verdict).toBe('PASS')});
  it('fails the same unknown word when it is required for the answer',()=>{const result=normalized([item({value:'ドラゴンフルーツ',support:'UNSUPPORTED',knowledgeUnitIds:[],sourceChunkIds:[],evidence:'No approved vocabulary support.',reason:'Its meaning distinguishes the answer.'})]);expect(result.issues.map(x=>x.code)).toContain('REQUIRED_VOCABULARY_UNSUPPORTED')});
  it('hard-fails hidden external cultural or legal knowledge',()=>{const result=normalized([item({type:'CULTURAL_BACKGROUND',value:'specific Japanese bicycle law',source:'BACKGROUND',support:'UNSUPPORTED',knowledgeUnitIds:[],sourceChunkIds:[],evidence:'Not stated in the passage.',reason:'The learner must know a legal rule.'})]);expect(result.issues.map(x=>x.code)).toContain('EXTERNAL_KNOWLEDGE_REQUIRED');expect(result.outsideKnowledge[0].requiredToSolve).toBe(true)});
  it('does not require a supplied Reading fact to be curriculum knowledge',()=>{const result=normalized([item(),item({type:'OTHER',value:'午後6時',role:'INCIDENTAL',support:'UNSUPPORTED',knowledgeUnitIds:[],sourceChunkIds:[],evidence:'Fact appears in passage.',reason:'It is read from the notice rather than memorized.'})]);expect(result.verdict).toBe('PASS')});
  it('does not require a supplied Listening fact to be memorized',()=>{const result=normalized([item({value:'会議'}),item({type:'OTHER',value:'3時',role:'INCIDENTAL',source:'AUDIO_SCRIPT',support:'UNSUPPORTED',knowledgeUnitIds:[],sourceChunkIds:[],evidence:'Fact appears in audio.',reason:'The time is supplied by the script.'})],{section:'listening',audioScript:'会議は3時からです。'});expect(result.verdict).toBe('PASS')});
  it('flags an advanced unsupported distractor and hard-fails when elimination requires it',()=>{const result=normalized([item(),item({type:'GRAMMAR',value:'～ざるを得ない',source:'CHOICE',choiceIndex:3,support:'UNSUPPORTED',knowledgeUnitIds:[],sourceChunkIds:[],evidence:'Advanced option.',reason:'Understanding it is required to eliminate the option.'})]);expect(result.issues.map(x=>x.code)).toEqual(expect.arrayContaining(['DISTRACTOR_OUT_OF_CURRICULUM','REQUIRED_GRAMMAR_UNSUPPORTED']));expect(result.hardFail).toBe(true)});
  it('reviews but does not hard-fail a nonessential advanced distractor',()=>{const result=normalized([item(),item({type:'GRAMMAR',value:'～ざるを得ない',role:'SUPPORTING',source:'CHOICE',choiceIndex:3,support:'UNSUPPORTED',knowledgeUnitIds:[],sourceChunkIds:[],evidence:'Advanced distractor.',reason:'It degrades the option set but is not needed to solve.'})]);expect(result).toMatchObject({verdict:'REVIEW',hardFail:false});expect(result.issues.map(x=>x.code)).toContain('DISTRACTOR_OUT_OF_CURRICULUM')});
  it('reviews partial support without hard failing',()=>{const result=normalized([item({support:'PARTIALLY_SUPPORTED',evidence:'Only the function is supported.',reason:'The exact grammar boundary is incomplete.'})]);expect(result).toMatchObject({verdict:'REVIEW',hardFail:false,coverage:{partialCount:1}});expect(result.issues.map(x=>x.code)).toContain('PARTIALLY_SUPPORTED')});
  it('reviews missing source provenance even when knowledge is supported',()=>{const result=normalized([item({sourceChunkIds:[]})],{sourceChunks:[]});expect(result).toMatchObject({verdict:'REVIEW',provenance:{complete:false}});expect(result.issues.map(x=>x.code)).toContain('PROVENANCE_INCOMPLETE')});
  it('marks provenance incomplete when no approved curriculum authority exists',()=>{const result=normalized([item({support:'AMBIGUOUS_SUPPORT',knowledgeUnitIds:[],sourceChunkIds:[],evidence:'No authoritative mapping.',reason:'Support cannot be traced.'})],{approvedKnowledgeUnits:[],sourceChunks:[],retrieval:retrieval({totalApprovedUnits:0,returnedUnitCount:0,intendedKnowledgeUnitIds:[],missingIntendedKnowledgeUnitIds:[]})});expect(result).toMatchObject({verdict:'REVIEW',provenance:{complete:false}});expect(result.provenance.missingEvidence).toContain('No approved KnowledgeUnit authority was supplied')});
  it.each(['PARTIALLY_SUPPORTED','AMBIGUOUS_SUPPORT'] as const)('marks %s without trace IDs as incomplete provenance',(support)=>{const result=normalized([item({support,knowledgeUnitIds:[],sourceChunkIds:[],evidence:'Semantic support only.',reason:'No trace IDs were supplied.'})]);expect(result.provenance.complete).toBe(false);expect(result.issues.map(x=>x.code)).toContain('PROVENANCE_INCOMPLETE')});
  it('reviews rather than false-fails when curriculum retrieval is incomplete',()=>{const result=normalized([item({type:'GRAMMAR',value:'～ざるを得ない',support:'UNSUPPORTED',knowledgeUnitIds:[],sourceChunkIds:[],evidence:'Not in retrieved subset.',reason:'No support in subset.'})],{retrieval:retrieval({complete:false,strategy:'INTENDED_PLUS_RELEVANT',reason:'Catalog truncated.'})});expect(result).toMatchObject({verdict:'REVIEW',hardFail:false});expect(result.issues.map(x=>x.code)).toContain('CURRICULUM_SEARCH_INCOMPLETE');expect(result.issues.map(x=>x.code)).not.toContain('REQUIRED_GRAMMAR_UNSUPPORTED')});
  it('reviews when an intended unit is missing or not approved',()=>{const result=normalized([item()],{retrieval:retrieval({missingIntendedKnowledgeUnitIds:['KU-DRAFT']})});expect(result).toMatchObject({verdict:'REVIEW',hardFail:false});expect(result.issues.map(x=>x.code)).toContain('INSUFFICIENT_CURRICULUM_EVIDENCE')});
  it('hard-fails positive curriculum contradiction even if retrieval is incomplete',()=>{const result=normalized([item({contradictedByCurriculum:true,reason:'Approved evidence explicitly teaches the opposite rule.'})],{retrieval:retrieval({complete:false,strategy:'INTENDED_PLUS_RELEVANT',reason:'Catalog truncated.'})});expect(result).toMatchObject({verdict:'FAIL',hardFail:true});expect(result.issues.map(x=>x.code)).toContain('CURRICULUM_CONTRADICTION')});
  it('reviews a low-confidence complete mapping',()=>{const result=normalized([item()],{},'LOW');expect(result).toMatchObject({verdict:'REVIEW',hardFail:false});expect(result.issues.map(x=>x.code)).toContain('LOW_CONFIDENCE')});
});

describe('QA4 extraction, retrieval and provider boundaries',()=>{
  afterEach(()=>{vi.unstubAllGlobals();delete process.env.CURRICULUM_GROUNDING_ENDPOINT});
  it('mock independently extracts unsupported advanced grammar',async()=>{const value=input({stem:'明日は休まざるを得ません。',choices:['はい','いいえ'],approvedKnowledgeUnits:[unit({vocabulary:['休み']})]});const result=finalizeCurriculumGrounding(await new MockCurriculumGroundingProvider().evaluate(value),value);expect(result.knowledgeAnalysis.some(x=>x.type==='GRAMMAR'&&x.value==='～ざるを得ない')).toBe(true);expect(result.verdict).toBe('FAIL')});
  it('keeps the conservative mock from passing unknown required vocabulary or kanji',async()=>{const value=input({instruction:'「受付」の読み方を選んでください。',stem:'「受付」はどう読みますか。',choices:['うけつけ','うけとり','じむしょ','かいぎ'],approvedKnowledgeUnits:[unit()]});const result=finalizeCurriculumGrounding(await new MockCurriculumGroundingProvider().evaluate(value),value);expect(result.knowledgeAnalysis.some(x=>x.value==='受付'&&(x.type==='KANJI'||x.type==='VOCABULARY')&&x.support!=='SUPPORTED')).toBe(true);expect(result.verdict).not.toBe('PASS')});
  it('does not classify a legal fact explicitly supplied in the passage as hidden background',async()=>{const value=input({stem:'日本の法律では、自転車は道路の左側を走ります。この文章によると、自転車はどちら側を走りますか。',choices:['左側','右側','どちらでもいい','書いていない']});const result=finalizeCurriculumGrounding(await new MockCurriculumGroundingProvider().evaluate(value),value);expect(result.knowledgeAnalysis.some(x=>x.type==='CULTURAL_BACKGROUND')).toBe(false);expect(result.issues.map(x=>x.code)).not.toContain('EXTERNAL_KNOWLEDGE_REQUIRED')});
  it('still hard-fails a legal rule requested without learner-visible support',async()=>{const value=input({stem:'日本の法律では、自転車はどちら側を走りますか。',choices:['左側','右側','どちらでもいい','決まりはない']});const result=finalizeCurriculumGrounding(await new MockCurriculumGroundingProvider().evaluate(value),value);expect(result.knowledgeAnalysis.some(x=>x.type==='CULTURAL_BACKGROUND'&&x.support==='UNSUPPORTED')).toBe(true);expect(result.issues.map(x=>x.code)).toContain('EXTERNAL_KNOWLEDGE_REQUIRED');expect(result.verdict).toBe('FAIL')});
  it('strictly rejects fabricated KnowledgeUnit and SourceChunk IDs',()=>{const value=input();expect(()=>validateCurriculumGroundingAnalysis(analysis([item({knowledgeUnitIds:['KU-FAKE']})]),value)).toThrow(CurriculumGroundingError);expect(()=>validateCurriculumGroundingAnalysis(analysis([item({sourceChunkIds:['SC-FAKE']})]),value)).toThrow(CurriculumGroundingError)});
  it('rejects a SourceChunk whose source document does not own the referenced KnowledgeUnit',()=>{const value=input({sourceChunks:[{id:'SC-1',sourceDocumentId:'SRC-OTHER',normalizedText:'Unrelated source.'}]});expect(()=>validateCurriculumGroundingAnalysis(analysis([item()]),value)).toThrow(CurriculumGroundingError)});
  it('keeps only approved authority and reports non-approved intended IDs missing',()=>{const approved={...unit(),status:'approved' as const} as KnowledgeUnit;const draft={...unit({id:'KU-DRAFT'}),status:'draft' as const} as KnowledgeUnit;const rejected={...unit({id:'KU-REJECTED'}),status:'rejected' as const} as KnowledgeUnit;const catalog:CurriculumCatalog={units:[approved,draft,rejected],searchedSourceDocumentIds:['SRC-1'],complete:true,failedSourceDocumentIds:[]};const job=jobFixture(['KU-DRAFT']);const selected=selectCurriculumUnits(catalog,candidate(),job,10);expect(selected.units.map(x=>x.id)).toEqual(['KU-BASIC']);expect(selected.retrieval.missingIntendedKnowledgeUnitIds).toEqual(['KU-DRAFT'])});
  it('marks capped retrieval incomplete while preserving an intended approved unit',()=>{const units=Array.from({length:12},(_,i)=>({...unit({id:`KU-${i}`,topic:`topic-${i}`}),status:'approved' as const} as KnowledgeUnit));const catalog:CurriculumCatalog={units,searchedSourceDocumentIds:['SRC-1'],complete:true,failedSourceDocumentIds:[]};const selected=selectCurriculumUnits(catalog,candidate(),jobFixture(['KU-11']),10);expect(selected.retrieval.complete).toBe(false);expect(selected.units.some(x=>x.id==='KU-11')).toBe(true);expect(selected.units).toHaveLength(10)});
  it('scopes approved authority to the target level or lower',()=>{const a1={...unit({id:'KU-A1',level:'A1'}),status:'approved' as const} as KnowledgeUnit;const a22={...unit({id:'KU-A22',level:'A2.2'}),status:'approved' as const} as KnowledgeUnit;const catalog:CurriculumCatalog={units:[a1,a22],searchedSourceDocumentIds:['SRC-1'],complete:true,failedSourceDocumentIds:[]};const selected=selectCurriculumUnits(catalog,candidate(question({level:'A1'})),jobFixture(['KU-A22']),10);expect(selected.units.map(x=>x.id)).toEqual(['KU-A1']);expect(selected.retrieval.totalApprovedUnits).toBe(1);expect(selected.retrieval.missingIntendedKnowledgeUnitIds).toContain('KU-A22')});
  it('HTTP provider receives only specialized input and versioned prompt',async()=>{process.env.CURRICULUM_GROUNDING_ENDPOINT='https://curriculum.test';let payload:any;vi.stubGlobal('fetch',vi.fn(async(_url,init)=>{payload=JSON.parse(String((init as RequestInit).body));return new Response(JSON.stringify(analysis([item()])),{status:200,headers:{'content-type':'application/json'}})}));const result=await new HttpCurriculumGroundingProvider().evaluate(input());expect(result.questionId).toBe('QA4-1');expect(payload.promptVersion).toBe(CURRICULUM_GROUNDING_PROMPT_VERSION);expect(payload.input).not.toHaveProperty('contentQa');expect(payload.input).not.toHaveProperty('answerOracleQa');expect(payload.input).not.toHaveProperty('japaneseNaturalnessQa')});
  it('turns invalid provider output and provider failure into technical REVIEW',async()=>{const c1=candidate();await runCurriculumGroundingGate(c1,input(),new StubProvider(()=>analysis([item({knowledgeUnitIds:['FABRICATED']})])));expect(c1.curriculumGroundingQa).toMatchObject({verdict:'REVIEW',issues:[{code:'CURRICULUM_GROUNDING_INVALID_OUTPUT'}]});const c2=candidate();await runCurriculumGroundingGate(c2,input(),new StubProvider(()=>{throw new Error('offline')}));expect(c2.curriculumGroundingQa).toMatchObject({verdict:'REVIEW',issues:[{code:'CURRICULUM_GROUNDING_PROVIDER_FAILURE'}]})});
  it('lets QA4 FAIL override QA1, QA2 and QA3 PASS',async()=>{const c=candidate();const raw=analysis([item({type:'GRAMMAR',value:'～ざるを得ない',support:'UNSUPPORTED',knowledgeUnitIds:[],sourceChunkIds:[],evidence:'No approved support.',reason:'Required to solve.'})]);await runCurriculumGroundingGate(c,input(),new StubProvider(()=>raw));expect(c.contentQa?.verdict).toBe('PASS');expect(c.answerOracleQa?.verdict).toBe('PASS');expect(c.japaneseNaturalnessQa?.verdict).toBe('PASS');expect(c.curriculumGroundingQa).toMatchObject({verdict:'FAIL',hardFail:true});expect(c.qa.passed).toBe(false);expect(c.qa.issues.some(x=>x.code==='curriculum_grounding_fail')).toBe(true)});
});

function jobFixture(ids:string[]):FactoryJob{return {id:'JOB-1',requestedBy:'admin',status:'review',request:{section:'reading',level:'A1',topic:'topic-11',canDo:'店の情報を理解する',count:1,difficulty:'balanced',includeExplanation:true,generateAudioScript:false},provider:'mock',createdAt:now,updatedAt:now,candidates:[],sourceContext:{sourceDocumentId:'SRC-1',sourceChunkIds:['SC-1'],knowledgeUnitId:ids[0],knowledgeUnitIds:ids,questionPlanId:'PLAN-1',objective:'test',sourceTexts:['test']}}}
