import {describe,expect,it} from 'vitest';
import {GenerationFailedError,ITEM_BLUEPRINT_VERSION,generateBlueprintItem,rotateChoices,runGeneratorPreflight,type BlueprintGenerationProvider,type CoreItemDraft,type ItemBlueprint} from '@/lib/server/generator-v2';
import {DeterministicBlueprintGenerationProvider} from '@/lib/server/generator-v2-provider';

const blueprint=(overrides:Partial<ItemBlueprint>={}):ItemBlueprint=>({blueprintVersion:ITEM_BLUEPRINT_VERSION,id:'pilot-1',level:'A1',section:'reading',category:'information_search',canDo:'find a simple opening time',topic:'shopping',knowledgeUnitIds:['KU-1'],targetKnowledge:['何時','開きます'],taskIntent:'Locate the opening time in a short shop notice.',stimulusRequirements:{format:'notice',maxLength:180,requiredFacts:['stimulus=【店のお知らせ】\n店は 9時に 開きます。','question=店は 何時に 開きますか。','explanationVi=Thông báo cho biết cửa hàng mở lúc 9 giờ.'],learnerVisibleContext:['shop notice']},reasoningPattern:'single-information-retrieval',answerContract:{oneCorrectAnswer:true,answerSource:'explicit_fact',correctValue:'9時',evidenceKey:'9時'},distractorContract:{count:3,sameSemanticType:true,source:'nearby_or_plausible_information',forbidNonsense:true,misconceptions:['8時','10時','11時']},templateId:'reading:information_search',generationSeed:'a1',...overrides});

describe('Question Generator V2 contracts',()=>{
  it('inherits immutable blueprint metadata and never auto-approves',async()=>{const result=await generateBlueprintItem(blueprint(),new DeterministicBlueprintGenerationProvider());expect(result.question.level).toBe('A1');expect(result.question.section).toBe('reading');expect(result.question.tags).toContain('category:information_search');expect(result.question.status).toBe('review');expect(result.status).toBe('REVIEW');expect(result.preflight.passed).toBe(true)});
  it('keeps the answer index correct after choice rotation',()=>{const result=rotateChoices(['正解','A','B','C'],0,3);expect(result.choices[result.answer]).toBe('正解');expect(result.answer).toBe(3)});
  it('rejects duplicate answer and distractors',()=>{const b=blueprint();const now=new Date().toISOString();const question={id:'q',section:'reading' as const,type:'choice' as const,level:'A1' as const,instruction:'文章を読んでください。',prompt:'【店】\n9時です。\n\n何時ですか。',choices:['9時','9時','10時','10時'],answer:0,explanationVi:'x',tags:[`category:${b.category}`,`can-do:${b.canDo}`],version:1,status:'review' as const,source:'ai' as const,createdAt:now,updatedAt:now};const result=runGeneratorPreflight(b,question);expect(result.passed).toBe(false);expect(result.issues.map(x=>x.code)).toContain('DUPLICATE_CHOICE')});
  it('requires a Listening script',()=>{const b=blueprint({section:'listening',category:'announcement_instruction',stimulusRequirements:{format:'announcement',maxLength:180,requiredFacts:[],learnerVisibleContext:[]}});const now=new Date().toISOString();const question={id:'q',section:'listening' as const,type:'audio_choice' as const,level:'A1' as const,instruction:'音声を聞いてください。',prompt:'何時ですか。',choices:['9時','8時','10時','11時'],answer:0,explanationVi:'x',tags:[`category:${b.category}`,`can-do:${b.canDo}`],version:1,status:'review' as const,source:'ai' as const,createdAt:now,updatedAt:now};expect(runGeneratorPreflight(b,question).issues.map(x=>x.code)).toContain('LISTENING_SCRIPT_MISSING')});
  it('requires a separated Reading stimulus',()=>{const b=blueprint();const now=new Date().toISOString();const question={id:'q',section:'reading' as const,type:'choice' as const,level:'A1' as const,instruction:'文章を読んでください。',prompt:'何時ですか。',choices:['9時','8時','10時','11時'],answer:0,explanationVi:'x',tags:[`category:${b.category}`,`can-do:${b.canDo}`],version:1,status:'review' as const,source:'ai' as const,createdAt:now,updatedAt:now};expect(runGeneratorPreflight(b,question).issues.map(x=>x.code)).toContain('READING_STIMULUS_MISSING')});
  it('bounds retry and keeps failed generation out of the candidate result',async()=>{let calls=0;const bad:BlueprintGenerationProvider={name:'bad',promptVersion:'bad-v1',async generateCore(b){calls++;return {instruction:'読んでください。',stimulus:'短い文',prompt:'質問です。',correctAnswer:b.answerContract.correctValue,answerEvidence:'none',explanationVi:'x',tags:[]}},async generateDistractors(_b,core){return {correctAnswer:core.correctAnswer,choices:[core.correctAnswer,core.correctAnswer,core.correctAnswer]}}};await expect(generateBlueprintItem(blueprint(),bad,{maxAttempts:3})).rejects.toBeInstanceOf(GenerationFailedError);expect(calls).toBe(3)});
  it('blocks provider attempts to mutate the contracted answer',async()=>{const base=new DeterministicBlueprintGenerationProvider();const mutating:BlueprintGenerationProvider={...base,name:'mutating',promptVersion:'mutating-v1',generateCore:async b=>({...await base.generateCore(b),correctAnswer:'10時'}),generateDistractors:(b,c)=>base.generateDistractors(b,c)};await expect(generateBlueprintItem(blueprint(),mutating,{maxAttempts:2})).rejects.toMatchObject({attempts:2})});
});
