import {describe,expect,it} from 'vitest';
import failure from '@/data/analysis/generator-failure-summary.json';
import gold from '@/data/gold/gold-seed-candidates.json';
import pilot from '@/data/pilots/generator-recovery-a1-pilot.json';
import pilot2 from '@/data/pilots/generator-recovery-a1-pilot-2.json';
import pilot1Review from '@/data/reviews/generator-recovery-a1-pilot-1-human-review.json';
import pilot2Review from '@/data/reviews/generator-recovery-a1-pilot-2-human-review.json';
import controlledBatch001 from '@/data/production/controlled-a1-batch-001.json';
import controlledBatch001Review from '@/data/reviews/controlled-a1-batch-001-human-review.json';
import controlledBatch002 from '@/data/production/controlled-a1-batch-002.json';
import controlledBatch002Review from '@/data/reviews/controlled-a1-batch-002-human-review.json';
import controlledBatch003 from '@/data/production/controlled-a1-batch-003.json';
import controlledBatch003Review from '@/data/reviews/controlled-a1-batch-003-human-review.json';
import controlledBatch004 from '@/data/production/controlled-a1-batch-004.json';

describe('generator recovery evidence',()=>{
  it('reconciles the historical corpus and stratified sample',()=>{expect(failure.summary.historicalItemCount).toBe(2050);expect(failure.records).toHaveLength(2038);expect(failure.rootCauseSample).toHaveLength(100);expect(new Set(failure.rootCauseSample.map(item=>item.level))).toEqual(new Set(['A1','A2.1','A2.2']));expect(new Set(failure.rootCauseSample.map(item=>item.section))).toEqual(new Set(['script_vocabulary','conversation_expression','listening','reading']))});
  it('uses only explicit KEEP evidence for Gold seed candidates',()=>{expect(gold.candidates).toHaveLength(12);expect(gold.candidates.every(item=>item.evidence.decision==='KEEP'&&item.evidence.confidence==='HIGH')).toBe(true)});
  it('records explicit human Gold evidence for all forty Pilot 1 items',()=>{expect(pilot.records).toHaveLength(40);expect(new Set(pilot.records.map(item=>item.question.id)).size).toBe(40);expect(pilot.records.every(item=>item.question.level==='A1'&&item.question.status==='review'&&item.preflight.passed&&item.humanReview.decision==='GOLD')).toBe(true);expect(pilot.summary.humanGoldYield).toBe(1);expect(pilot1Review.summary).toMatchObject({reviewed:40,gold:40,humanGoldYield:1});expect(pilot.manualPreEvaluationEdits).toBe(0);expect(pilot.frozenBeforeHumanReview).toBe(true)});
  it('keeps the 10/10/10/10 section distribution',()=>{for(const section of ['script_vocabulary','conversation_expression','listening','reading'])expect(pilot.records.filter(item=>item.question.section===section)).toHaveLength(10)});
  it('stores separate QA1-QA7 evidence for every Pilot 1 item',()=>{expect(pilot.records.every(item=>['qa1','qa2','qa3','qa4','qa5','qa6','qa7'].every(key=>item.qa[key as keyof typeof item.qa]))).toBe(true)});
  it('records explicit human Gold evidence for all forty fresh Pilot 2 items',()=>{expect(pilot2.records).toHaveLength(40);expect(new Set(pilot2.records.map(item=>item.question.id)).size).toBe(40);expect(pilot2.records.every(item=>item.question.level==='A1'&&item.question.status==='review'&&item.preflight.passed&&item.humanReview.decision==='GOLD')).toBe(true);expect(pilot2.manualPreEvaluationEdits).toBe(0);expect(pilot2.frozenBeforeHumanReview).toBe(true);expect(pilot2.summary.humanGoldYield).toBe(1);expect(pilot2Review.summary).toMatchObject({reviewed:40,gold:40,humanGoldYield:1});expect(pilot2.records.some(item=>pilot.records.some(first=>first.question.id===item.question.id))).toBe(false)});
  it('keeps Pilot 2 at 10/10/10/10 and stores QA1-QA7 independently',()=>{for(const section of ['script_vocabulary','conversation_expression','listening','reading'])expect(pilot2.records.filter(item=>item.question.section===section)).toHaveLength(10);expect(pilot2.records.every(item=>['qa1','qa2','qa3','qa4','qa5','qa6','qa7'].every(key=>item.qa[key as keyof typeof item.qa]))).toBe(true)});
  it('records explicit Gold review for Controlled A1 Batch 001 without changing bank status',()=>{expect(controlledBatch001.records).toHaveLength(20);expect(controlledBatch001).toMatchObject({artifactVersion:'CONTROLLED_A1_BATCH_001_V1',runMode:'scale-001',manualPreEvaluationEdits:0,frozenBeforeHumanReview:true});expect(new Set(controlledBatch001.records.map(item=>item.question.id)).size).toBe(20);for(const section of ['script_vocabulary','conversation_expression','listening','reading'])expect(controlledBatch001.records.filter(item=>item.question.section===section)).toHaveLength(5);expect(controlledBatch001.records.every(item=>item.question.status==='review'&&item.preflight.passed&&item.humanReview.decision==='GOLD'&&['qa1','qa2','qa3','qa4','qa5','qa6','qa7'].every(key=>item.qa[key as keyof typeof item.qa]))).toBe(true);expect(controlledBatch001.summary.humanGoldYield).toBe(1);expect(controlledBatch001Review.summary).toMatchObject({reviewed:20,gold:20,humanGoldYield:1})});
  it('keeps Controlled Batch IDs separate and reports operational dimensions',()=>{const priorIds=new Set([...pilot.records,...pilot2.records].map(item=>item.question.id));expect(controlledBatch001.records.some(item=>priorIds.has(item.question.id))).toBe(false);expect(Object.keys(controlledBatch001.summary.byCategory).length).toBeGreaterThan(4);expect(Object.keys(controlledBatch001.summary.byCanDo)).toHaveLength(20);expect(Object.keys(controlledBatch001.summary.byTemplate)).toHaveLength(20)});
  it('records explicit Gold review for Controlled A1 Batch 002',()=>{expect(controlledBatch002.records).toHaveLength(20);expect(controlledBatch002).toMatchObject({artifactVersion:'CONTROLLED_A1_BATCH_002_V1',runMode:'scale-002',manualPreEvaluationEdits:0,frozenBeforeHumanReview:true});const priorIds=new Set([...pilot.records,...pilot2.records,...controlledBatch001.records].map(item=>item.question.id));expect(controlledBatch002.records.some(item=>priorIds.has(item.question.id))).toBe(false);for(const section of ['script_vocabulary','conversation_expression','listening','reading'])expect(controlledBatch002.records.filter(item=>item.question.section===section)).toHaveLength(5);expect(controlledBatch002.records.every(item=>item.question.status==='review'&&item.preflight.passed&&item.humanReview.decision==='GOLD')).toBe(true);expect(controlledBatch002.summary).toMatchObject({generated:20,preflightPass:20,humanGold:20,humanReviewStatus:'COMPLETED',humanGoldYield:1});expect(controlledBatch002Review.summary).toMatchObject({reviewed:20,gold:20,humanGoldYield:1})});
  it('records explicit Gold review for Controlled A1 Batch 003',()=>{expect(controlledBatch003.records).toHaveLength(20);expect(controlledBatch003).toMatchObject({artifactVersion:'CONTROLLED_A1_BATCH_003_V1',runMode:'scale-003',manualPreEvaluationEdits:0,frozenBeforeHumanReview:true});const priorIds=new Set([...pilot.records,...pilot2.records,...controlledBatch001.records,...controlledBatch002.records].map(item=>item.question.id));expect(controlledBatch003.records.some(item=>priorIds.has(item.question.id))).toBe(false);expect(controlledBatch003.records.every(item=>item.question.status==='review'&&item.preflight.passed&&item.humanReview.decision==='GOLD')).toBe(true);expect(controlledBatch003.summary).toMatchObject({generated:20,preflightPass:20,humanGold:20,humanReviewStatus:'COMPLETED',humanGoldYield:1});expect(controlledBatch003Review.summary).toMatchObject({reviewed:20,gold:20,humanGoldYield:1})});
  it('records explicit Gold review for Controlled A1 Batch 004 without automatic bank approval',()=>{expect(controlledBatch004.records).toHaveLength(20);expect(controlledBatch004).toMatchObject({artifactVersion:'CONTROLLED_A1_BATCH_004_V1',runMode:'scale-004',manualPreEvaluationEdits:0,frozenBeforeHumanReview:true});const priorIds=new Set([...pilot.records,...pilot2.records,...controlledBatch001.records,...controlledBatch002.records,...controlledBatch003.records].map(item=>item.question.id));expect(controlledBatch004.records.some(item=>priorIds.has(item.question.id))).toBe(false);for(const section of ['script_vocabulary','conversation_expression','listening','reading'])expect(controlledBatch004.records.filter(item=>item.question.section===section)).toHaveLength(5);expect(controlledBatch004.records.every(item=>item.question.status==='review'&&item.preflight.passed&&item.humanReview.decision==='GOLD')).toBe(true);expect(controlledBatch004.summary).toMatchObject({generated:20,preflightPass:20,humanGold:20,humanReviewStatus:'COMPLETED',humanGoldYield:1})});
});
