import {afterEach,describe,expect,it,vi} from 'vitest';
import type {QuestionRecord} from '@/lib/admin-types';
import type {FactoryCandidate} from '@/lib/server/factory-domain';
import {buildJapaneseNaturalnessInput,finalizeJapaneseNaturalnessAssessment,JapaneseNaturalnessError,JAPANESE_NATURALNESS_PROMPT_VERSION,validateJapaneseNaturalnessOutput,type JapaneseNaturalnessAssessment,type JapaneseNaturalnessInput} from '@/lib/server/japanese-naturalness';
import {HttpJapaneseNaturalnessProvider,MockJapaneseNaturalnessProvider,type JapaneseNaturalnessProvider} from '@/lib/server/japanese-naturalness-provider';
import {runJapaneseNaturalnessGate} from '@/lib/server/factory-service';

const now='2026-08-18T00:00:00.000Z';
function question(overrides:Partial<QuestionRecord>={}):QuestionRecord{return {id:'QA3-1',section:'conversation_expression',type:'choice',level:'A1',instruction:'いちばんいいものを選んでください。',prompt:'A：すみません、牛乳はどこですか。\nB：あちらの冷蔵庫にあります。',choices:['あちらの冷蔵庫です。','レジの後ろです。','店の外です。','二階です。'],answer:0,explanationVi:'Trong tủ lạnh phía kia.',tags:['shopping'],version:1,status:'review',source:'ai',createdAt:now,updatedAt:now,...overrides}}
const provider=new MockJapaneseNaturalnessProvider();
async function judge(q:QuestionRecord,audioScript?:string){const input=buildJapaneseNaturalnessInput(q,{audioScript,topic:'daily life'});return provider.judge(input)}
function codes(result:JapaneseNaturalnessAssessment){return result.issues.map(issue=>issue.code)}
function highAssessment(input:JapaneseNaturalnessInput,overrides:Partial<JapaneseNaturalnessAssessment>={}):JapaneseNaturalnessAssessment{return finalizeJapaneseNaturalnessAssessment({qaVersion:JAPANESE_NATURALNESS_PROMPT_VERSION,questionId:input.questionId,confidence:'HIGH',scores:{grammar:20,naturalness:20,collocation:15,register:15,contextFit:10,spokenWrittenFit:10,conversationFlow:10,overall:100},contextAssessment:{declaredContext:input.declaredContext,actualStyle:'SPOKEN',fit:'GOOD'},choiceLanguageAnalysis:input.choices.map((_,index)=>({index,natural:true,issues:[]})),issues:[],...overrides})}
class StubProvider implements JapaneseNaturalnessProvider{constructor(private fn:(input:JapaneseNaturalnessInput)=>Promise<JapaneseNaturalnessAssessment>|JapaneseNaturalnessAssessment){}name='stub-naturalness';model='test';judge(input:JapaneseNaturalnessInput){return Promise.resolve(this.fn(input))}}

describe('QA3 Japanese language dimensions',()=>{
  it('passes natural everyday Japanese',async()=>{const result=await judge(question());expect(result).toMatchObject({verdict:'PASS',hardFail:false,confidence:'HIGH'});expect(result.issues).toEqual([])});
  it('flags grammatically possible but unnatural bureaucratic wording',async()=>{const result=await judge(question({prompt:'A：明日は何をしますか。\nB：スーパーで買い物を実施します。'}));expect(codes(result)).toContain('UNNATURAL_WORD_CHOICE');expect(result.verdict).not.toBe('PASS')});
  it('detects a wrong particle',async()=>{const result=await judge(question({prompt:'私は日曜日で友達に会います。'}));expect(codes(result)).toContain('PARTICLE_ERROR');expect(result.scores.grammar).toBeLessThan(20)});
  it('detects an unnatural collocation',async()=>{const result=await judge(question({prompt:'風邪なので、薬を食べました。'}));expect(codes(result)).toContain('UNNATURAL_COLLOCATION');expect(result.scores.collocation).toBeLessThan(15)});
  it('hard-fails a severe overly formal friends conversation',async()=>{const result=await judge(question({prompt:'A：明日、映画を見ない？\nB：承知いたしました。午後二時に参上いたします。'}));expect(codes(result)).toContain('SEVERE_REGISTER_MISMATCH');expect(result).toMatchObject({verdict:'FAIL',hardFail:true,release:{eligibleToProceed:false,requiresHumanReview:true}})});
  it('flags an overly casual public notice and recognizes spoken style',async()=>{const result=await judge(question({section:'reading',prompt:'【お知らせ】ゴミはここに捨てないでね。ちゃんと持って帰って。'}));expect(codes(result)).toContain('REGISTER_TOO_CASUAL');expect(result.contextAssessment.actualStyle).toBe('SPOKEN')});
  it('detects keigo misuse',async()=>{const result=await judge(question({prompt:'店員：お客様がもう参りました。'}));expect(codes(result)).toContain('KEIGO_MISUSE');expect(result.scores.register).toBeLessThan(15)});
  it('flags a written-style Listening script without judging audio quality',async()=>{const q=question({section:'listening',type:'audio_choice',prompt:'作業の前に何をしますか。'});const result=await judge(q,'作業開始に先立ち、当該機器の電源状態を確認するものとする。');expect(codes(result)).toContain('WRITTEN_STYLE_IN_SPOKEN_CONTEXT');expect(result.contextAssessment.actualStyle).toBe('WRITTEN');expect(JSON.stringify(result)).not.toContain('pronunciation')});
  it('detects artificial dialogue flow',async()=>{const result=await judge(question({prompt:'A：明日の会議は何時からですか。\nB：はい、駅でパンを買いました。'}));expect(codes(result)).toContain('ARTIFICIAL_DIALOGUE_FLOW');expect(result.scores.conversationFlow).toBeLessThan(10)});
  it('hard-fails malformed distractors that leak the answer',async()=>{const result=await judge(question({section:'reading',prompt:'店は九時に開きます。',choices:['九時です。','八時ます。','十時を開き。','十一時でする。']}));expect(codes(result)).toContain('LANGUAGE_ERROR_LEAKS_CORRECT_ANSWER');expect(result).toMatchObject({verdict:'FAIL',hardFail:true});expect(result.choiceLanguageAnalysis.slice(1).every(choice=>!choice.natural)).toBe(true)});
  it('routes a high-scoring low-confidence judgment to REVIEW',()=>{const input=buildJapaneseNaturalnessInput(question());const result=highAssessment(input,{confidence:'LOW'});expect(result).toMatchObject({verdict:'REVIEW',hardFail:false});expect(result.release.eligibleToProceed).toBe(false)});
});

describe('QA3 validation and pipeline integration',()=>{
  afterEach(()=>{vi.unstubAllGlobals();delete process.env.JAPANESE_NATURALNESS_ENDPOINT});
  it('strictly rejects invalid provider output',()=>{const input=buildJapaneseNaturalnessInput(question());const result=highAssessment(input);expect(()=>validateJapaneseNaturalnessOutput({...result,scores:{...result.scores,grammar:21,overall:101}},input)).toThrow(JapaneseNaturalnessError)});
  it('requires language analysis for every choice',()=>{const input=buildJapaneseNaturalnessInput(question());const result=highAssessment(input);expect(()=>validateJapaneseNaturalnessOutput({...result,choiceLanguageAnalysis:result.choiceLanguageAnalysis.slice(1)},input)).toThrow(/Every choice/)});
  it('rejects a choice issue that lacks corresponding top-level evidence',()=>{const input=buildJapaneseNaturalnessInput(question());const result=highAssessment(input);const choices=result.choiceLanguageAnalysis.map((choice,index)=>index===1?{...choice,natural:false,issues:['LANGUAGE_ERROR_LEAKS_CORRECT_ANSWER' as const]}:choice);expect(()=>validateJapaneseNaturalnessOutput({...result,choiceLanguageAnalysis:choices},input)).toThrow(/top-level evidence/)});
  it('stores technical provider failures as REVIEW rather than PASS',async()=>{const c={id:'candidate',question:question(),qa:{passed:true,score:97,issues:[]},generation:{provider:'generator',promptVersion:'v1',createdAt:now}} as FactoryCandidate;await runJapaneseNaturalnessGate(c,{},new StubProvider(()=>{throw new Error('offline')}));expect(c.japaneseNaturalnessQa).toMatchObject({verdict:'REVIEW',confidence:'LOW'});expect(c.qa.issues.some(issue=>issue.code==='japanese_naturalness_review')).toBe(true)});
  it('converts an invalid injected provider result to technical REVIEW',async()=>{const c={id:'candidate',question:question(),qa:{passed:true,score:97,issues:[]},generation:{provider:'generator',promptVersion:'v1',createdAt:now}} as FactoryCandidate;await runJapaneseNaturalnessGate(c,{},new StubProvider(input=>({...highAssessment(input),scores:{...highAssessment(input).scores,grammar:99}} as JapaneseNaturalnessAssessment)));expect(c.japaneseNaturalnessQa?.issues[0].code).toBe('JAPANESE_NATURALNESS_INVALID_OUTPUT');expect(c.japaneseNaturalnessQa?.verdict).toBe('REVIEW')});
  it('validates HTTP provider evidence and sends no earlier QA scores',async()=>{process.env.JAPANESE_NATURALNESS_ENDPOINT='https://naturalness.test';let payload:any;vi.stubGlobal('fetch',vi.fn(async(_url,init)=>{payload=JSON.parse(String((init as RequestInit).body));return new Response(JSON.stringify(highAssessment(payload.input)),{status:200,headers:{'content-type':'application/json'}})}));const result=await new HttpJapaneseNaturalnessProvider().judge(buildJapaneseNaturalnessInput(question()));expect(result.verdict).toBe('PASS');expect(payload.promptVersion).toBe(JAPANESE_NATURALNESS_PROMPT_VERSION);expect(payload.systemInstruction).toContain('spoken-versus-written');expect(payload.input).not.toHaveProperty('contentQa');expect(payload.input).not.toHaveProperty('answerOracleQa')});
  it('allows QA3 FAIL to override QA1 PASS and QA2 PASS',async()=>{const c={id:'candidate',question:question(),qa:{passed:true,score:97,issues:[]},generation:{provider:'generator',promptVersion:'v1',createdAt:now},contentQa:{verdict:'PASS'},answerOracleQa:{verdict:'PASS'}} as unknown as FactoryCandidate;const failing=new StubProvider(input=>{const base=highAssessment(input);return finalizeJapaneseNaturalnessAssessment({...base,issues:[{code:'BROKEN_JAPANESE',severity:'CRITICAL',evidence:'私がは',reason:'Broken particles.',suggestedAction:'Revise the affected language.'}]})});await runJapaneseNaturalnessGate(c,{},failing);expect(c.contentQa?.verdict).toBe('PASS');expect(c.answerOracleQa?.verdict).toBe('PASS');expect(c.japaneseNaturalnessQa).toMatchObject({verdict:'FAIL',hardFail:true});expect(c.qa.passed).toBe(false)});
});
