import {afterEach,describe,expect,it,vi} from 'vitest';
import type {QuestionRecord} from '@/lib/admin-types';
import type {FactoryCandidate} from '@/lib/server/factory-domain';
import {buildOriginalityDuplicateInput,finalizeOriginalityDuplicate,ORIGINALITY_DUPLICATE_PROMPT_VERSION,summarizeOriginalityDuplicateMetrics,validateOriginalityDuplicateAnalysis,withOriginalityDuplicateAudit,type OriginalityCorpusItem,type OriginalityDuplicateAnalysis,type OriginalityDuplicateInput} from '@/lib/server/originality-duplicate';
import {HttpOriginalityDuplicateProvider,MockOriginalityDuplicateProvider,type OriginalityDuplicateProvider} from '@/lib/server/originality-duplicate-provider';
import {runOriginalityDuplicateGate} from '@/lib/server/factory-service';

const now='2026-08-23T00:00:00.000Z';
function question(patch:Partial<QuestionRecord>={}):QuestionRecord{return {id:'AI-READING-REAL-LEVEL-A1',section:'reading',type:'choice',level:'A1',instruction:'文を読んで答えてください。',prompt:'さくら店は午後6時に閉まります。店は何時に閉まりますか。',choices:['午後4時','午後5時','午後6時','午後7時'],answer:2,explanationVi:'Cửa hàng đóng cửa lúc 6 giờ.',tags:['shopping'],version:1,status:'review',source:'ai',createdAt:now,updatedAt:now,...patch}}
function input(corpus:OriginalityCorpusItem[],patch:Partial<QuestionRecord>={}){return buildOriginalityDuplicateInput(question(patch),{sourceExpected:corpus.some(item=>item.kind==='SOURCE'),corpus})}
async function result(value:OriginalityDuplicateInput){const provider=new MockOriginalityDuplicateProvider();return finalizeOriginalityDuplicate(validateOriginalityDuplicateAnalysis(await provider.analyze(value),value),value,question().id)}
function candidate(q=question()):FactoryCandidate{return {id:'candidate',question:q,qa:{passed:true,score:100,issues:[]},generation:{provider:'test-generator',promptVersion:'test-v1',createdAt:now}}}

describe('QA7 originality and duplicate policy',()=>{
  afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs()});

  it('hard-fails a normalized source copy',async()=>{const value=input([{id:'SC-1',kind:'SOURCE',text:'さくら店は午後6時に閉まります。店は何時に閉まりますか。'}]);const qa=await result(value);expect(qa).toMatchObject({verdict:'FAIL',hardFail:true});expect(qa.issues.map(item=>item.code)).toContain('SOURCE_COPY_CONFIRMED')});

  it('detects superficial name and number substitutions as source copying',async()=>{const q=question({prompt:'山田さんは店でりんごを5つ買いました。りんごはいくつ買いましたか。',choices:['2つ','3つ','4つ','5つ']});const value=buildOriginalityDuplicateInput(q,{sourceExpected:true,corpus:[{id:'SC-2',kind:'SOURCE',text:'田中さんは店でりんごを3つ買いました。りんごはいくつ買いましたか。'}]});const comparison=value.comparisons[0];expect(comparison.patternSimilarity).toBeGreaterThanOrEqual(.94);expect((await result(value)).verdict).toBe('FAIL')});

  it('passes a distinct task that only shares curriculum topic vocabulary',async()=>{const value=input([{id:'SC-3',kind:'SOURCE',text:'店で値段を聞くときは「これはいくらですか」と言います。'}]);const qa=await result(value);expect(qa.verdict).toBe('PASS');expect(qa.summary.sourceCopyRisk).not.toBe('HIGH')});

  it.each(['BANK','BATCH'] as const)('hard-fails an exact %s duplicate',async kind=>{const value=input([{id:`${kind}-1`,kind,text:`文を読んで答えてください。 ${question().prompt} ${question().choices.join(' ')}`}]);const qa=await result(value);expect(qa.verdict).toBe('FAIL');expect(kind==='BANK'?qa.summary.bankDuplicateRisk:qa.summary.batchDuplicateRisk).toBe('HIGH')});

  it('routes medium overlap and low-confidence classification to REVIEW',async()=>{const value=input([{id:'BANK-MEDIUM',kind:'BANK',text:'さくら店は午後6時に閉まります。営業時間を見て答えます。'}]);value.comparisons[0].ngramSimilarity=.78;value.comparisons[0].patternSimilarity=.78;value.comparisons[0].containmentSimilarity=.8;const analysis:OriginalityDuplicateAnalysis={qaVersion:ORIGINALITY_DUPLICATE_PROMPT_VERSION,questionId:value.questionId,confidence:'LOW',relationships:[{comparisonId:'BANK-MEDIUM',kind:'BANK',semanticRisk:'MEDIUM',relationship:'NEAR_DUPLICATE',evidence:'The same practical decision may remain.'}]};const qa=finalizeOriginalityDuplicate(analysis,value,'Q');expect(qa.verdict).toBe('REVIEW');expect(qa.issues.map(item=>item.code)).toEqual(expect.arrayContaining(['DUPLICATE_RISK','LOW_CONFIDENCE']))});

  it('requires source evidence for a source-grounded job',async()=>{const value=buildOriginalityDuplicateInput(question(),{sourceExpected:true,corpus:[]});const qa=await result(value);expect(qa).toMatchObject({verdict:'REVIEW',hardFail:false});expect(qa.issues.map(item=>item.code)).toContain('SOURCE_EVIDENCE_MISSING')});

  it('strictly rejects fabricated relationship ids and extra provider fields',()=>{const value=input([{id:'BANK-1',kind:'BANK',text:'別の問題です。'}]);expect(()=>validateOriginalityDuplicateAnalysis({qaVersion:ORIGINALITY_DUPLICATE_PROMPT_VERSION,questionId:value.questionId,confidence:'HIGH',relationships:[{comparisonId:'FAKE',kind:'BANK',semanticRisk:'NONE',relationship:'DISTINCT',evidence:'Distinct.'}]},value)).toThrow(/fabricated/);expect(()=>validateOriginalityDuplicateAnalysis({qaVersion:ORIGINALITY_DUPLICATE_PROMPT_VERSION,questionId:value.questionId,confidence:'HIGH',relationships:[],verdict:'PASS'},value)).toThrow(/contract/)});

  it('turns invalid provider output and provider failure into technical REVIEW',async()=>{const value=buildOriginalityDuplicateInput(question(),{sourceExpected:false,corpus:[]});const invalid:OriginalityDuplicateProvider={name:'invalid',async analyze(){return {verdict:'PASS'}}};const failed:OriginalityDuplicateProvider={name:'failed',async analyze(){throw new Error('offline')}};const first=candidate();await runOriginalityDuplicateGate(first,value,invalid);expect(first.originalityDuplicateQa).toMatchObject({verdict:'REVIEW',confidence:'LOW'});const second=candidate();await runOriginalityDuplicateGate(second,value,failed);expect(second.originalityDuplicateQa?.issues.map(item=>item.code)).toContain('ORIGINALITY_DUPLICATE_PROVIDER_FAILURE')});

  it('keeps the HTTP classification request blind to answers, explanations, prior QA and level-bearing ids',async()=>{vi.stubEnv('ORIGINALITY_DUPLICATE_ENDPOINT','https://qa7.test/analyze');vi.stubEnv('ORIGINALITY_DUPLICATE_API_KEY','secret');const q=question({id:'AI-READING-A1-SECRET',answer:2,explanationVi:'EXPLANATION-SECRET'}),value=buildOriginalityDuplicateInput(q,{sourceExpected:false,corpus:[]});let serialized='';vi.stubGlobal('fetch',vi.fn(async(_url,init)=>{serialized=String((init as RequestInit).body);const payload=JSON.parse(serialized);return new Response(JSON.stringify({qaVersion:ORIGINALITY_DUPLICATE_PROMPT_VERSION,questionId:payload.input.questionId,confidence:'HIGH',relationships:[]}),{status:200,headers:{'content-type':'application/json'}})}));await new HttpOriginalityDuplicateProvider().analyze(value);expect(value.questionId).toMatch(/^QA7-/);expect(serialized).not.toContain('AI-READING-A1-SECRET');expect(serialized).not.toContain('EXPLANATION-SECRET');expect(serialized).not.toContain('answerOracleQa');expect(serialized).not.toContain('difficultyCalibrationQa');expect(JSON.parse(serialized).input).not.toHaveProperty('answer')});

  it('stores QA7 independently and cannot rescue an earlier gate failure',async()=>{const q=question(),value=buildOriginalityDuplicateInput(q,{sourceExpected:false,corpus:[]});const c=candidate(q);const sentinels={contentQa:{verdict:'PASS'},answerOracleQa:{verdict:'PASS'},japaneseNaturalnessQa:{verdict:'PASS'},curriculumGroundingQa:{verdict:'PASS'},jftAlignmentQa:{verdict:'FAIL'},difficultyCalibrationQa:{verdict:'PASS'}};Object.assign(c,sentinels);c.qa.passed=false;c.qa.issues.push({code:'jft_alignment_fail',severity:'error',category:'jft_style',message:'Earlier failure.'});await runOriginalityDuplicateGate(c,value,new MockOriginalityDuplicateProvider());expect(c.originalityDuplicateQa?.verdict).toBe('PASS');expect(c.qa.passed).toBe(false);expect(c.jftAlignmentQa).toEqual(sentinels.jftAlignmentQa)});

  it('reports nullable metrics and excludes technical reviews from content rates',async()=>{const pass=withOriginalityDuplicateAudit(await result(buildOriginalityDuplicateInput(question(),{sourceExpected:false,corpus:[]})),{provider:'mock'});const technical=candidate();await runOriginalityDuplicateGate(technical,buildOriginalityDuplicateInput(question(),{sourceExpected:false,corpus:[]}),{name:'bad',async analyze(){throw new Error('offline')}});const metrics=summarizeOriginalityDuplicateMetrics([pass,technical.originalityDuplicateQa!]);expect(metrics).toMatchObject({originalitySampleCount:2,originalityEvaluableSampleCount:1,originalityTechnicalReviewCount:1,sourceCopyFailureRate:0})});
});
