'use client';
import { useEffect,useMemo,useRef,useState } from 'react'; import { useRouter } from 'next/navigation'; import { candidateApi,CandidateExam,CandidateSession } from '@/lib/api-client'; import { SectionId } from '@/lib/types'; import { Alert,Skeleton } from '@/components/ui';
const SESSION_KEY='jft-v42-active-session';
const labels:Record<SectionId,string>={script_vocabulary:'Chữ viết & Từ vựng',conversation_expression:'Hội thoại & Biểu đạt',listening:'Nghe hiểu',reading:'Đọc hiểu'};
type Phase='loading'|'instructions'|'audio_check'|'section_intro'|'testing'|'section_confirm'|'final_confirm'|'expired'|'error';
export default function ExamClient(){
 const bootstrapped=useRef(false);
 const router=useRouter(),audioRef=useRef<HTMLAudioElement|null>(null);const [phase,setPhase]=useState<Phase>('loading'),[exam,setExam]=useState<CandidateExam|null>(null),[session,setSession]=useState<CandidateSession|null>(null),[currentIndex,setCurrentIndex]=useState(0),[answers,setAnswers]=useState<Record<string,number>>({}),[remaining,setRemaining]=useState(0),[language,setLanguage]=useState<'ja'|'vi'>('ja'),[error,setError]=useState(''),[sync,setSync]=useState<'idle'|'saving'|'saved'|'error'>('idle'),[plays,setPlays]=useState<Record<string,number>>({});
 useEffect(()=>{if(bootstrapped.current)return;bootstrapped.current=true;void bootstrap()},[]);useEffect(()=>{if(!session||session.status!=='active')return;const tick=()=>{const left=Math.max(0,new Date(session.expiresAt).getTime()-Date.now());setRemaining(left);if(left===0)void finish()};tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[session]);
 async function bootstrap(){try{let id=localStorage.getItem(SESSION_KEY);if(!id){const mine=await candidateApi.attempts();id=mine.attempts.find(a=>a.status==='active'&&Date.now()<new Date(a.expiresAt).getTime())?.id||null}if(id){try{const r=await candidateApi.resume(id);if(r.session.status==='active'&&Date.now()<new Date(r.session.expiresAt).getTime()){localStorage.setItem(SESSION_KEY,r.session.id);setSession(r.session);setExam(r.exam);setAnswers(r.session.answers||{});setCurrentIndex(r.session.currentIndex||0);setPhase('testing');return}}catch{localStorage.removeItem(SESSION_KEY)}}const latest=await candidateApi.latestExam();if(!latest.version){setError('Hiện chưa có bài luyện tập khả dụng. Vui lòng quay lại sau.');setPhase('error');return}setPhase('instructions')}catch{setError('Không thể kết nối với bài luyện tập. Vui lòng kiểm tra mạng và thử lại.');setPhase('error')}}
 async function startExam(){try{setPhase('loading');const latest=await candidateApi.latestExam();if(!latest.version)throw new Error();const r=await candidateApi.createSession(latest.version.id);setSession(r.session);setExam(r.exam);setAnswers(r.session.answers||{});setCurrentIndex(r.session.currentIndex||0);localStorage.setItem(SESSION_KEY,r.session.id);setPhase('section_intro')}catch{setError('Không thể bắt đầu bài luyện tập lúc này.');setPhase('error')}}
 const q=exam?.questions[currentIndex],rule=exam&&q?exam.rules.find(r=>r.section===q.section):undefined,sectionQuestions=useMemo(()=>exam&&q?exam.questions.map((x,i)=>({x,i})).filter(z=>z.x.section===q.section):[],[exam,q]);
 async function persist(index:number,id?:string,choice?:number){if(!session)return;try{setSync('saving');await candidateApi.saveAnswer(session.id,id,choice,index);setSync('saved')}catch{setSync('error')}}
 function choose(i:number){if(!q)return;setAnswers(a=>({...a,[q.id]:i}));void persist(currentIndex,q.id,i)}
 function go(index:number){if(!exam||!q)return;const next=Math.max(0,Math.min(exam.questions.length-1,index));if(!rule?.allowBack&&next<currentIndex)return;if(exam.questions[next].section!==q.section)return;setCurrentIndex(next);void persist(next)}
 function advance(){if(!exam||!q)return;if(currentIndex===exam.questions.length-1){setPhase('final_confirm');return}const next=currentIndex+1;if(exam.questions[next].section!==q.section){setPhase('section_confirm');return}setCurrentIndex(next);void persist(next)}
 function enterNextSection(){if(!exam)return;const next=currentIndex+1;setCurrentIndex(next);void persist(next);setPhase('section_intro')}
 async function finish(){if(!session)return;try{setPhase('loading');await candidateApi.submit(session.id);localStorage.removeItem(SESSION_KEY);router.push(`/result?sessionId=${encodeURIComponent(session.id)}`)}catch{setError('Không thể nộp bài ngay lúc này. Đáp án đã lưu; vui lòng thử lại.');setPhase('error')}}
 function playAudio(){if(!q?.audioSrc||!audioRef.current)return;const used=plays[q.id]||0;if(used>=2)return;audioRef.current.currentTime=0;audioRef.current.play().then(()=>setPlays(p=>({...p,[q.id]:used+1}))).catch(()=>setError('Không thể phát âm thanh. Hãy kiểm tra loa hoặc tai nghe.'))}
 const mins=String(Math.floor(remaining/60000)).padStart(2,'0'),secs=String(Math.floor((remaining%60000)/1000)).padStart(2,'0'),timer=`${mins}:${secs}`;
 if(phase==='loading')return <Frame timer="--:--"><section className="exam-stage"><Skeleton lines={4}/><p>Đang chuẩn bị bài luyện tập…</p></section></Frame>;
 if(phase==='error'||phase==='expired')return <Frame timer={phase==='expired'?'00:00':'--:--'}><section className="exam-stage"><span className="step">{phase==='expired'?'ĐÃ HẾT THỜI GIAN':'KHÔNG THỂ TIẾP TỤC'}</span><h1>{phase==='expired'?'Bài luyện tập đã kết thúc':'Đã xảy ra sự cố'}</h1><Alert tone={phase==='expired'?'warning':'danger'}>{error||'Hệ thống đã tự hoàn tất bài khi hết thời gian.'}</Alert><button className="primary" onClick={()=>phase==='error'?location.reload():router.replace('/candidate')}>{phase==='error'?'Thử lại':'Về trang chủ'}</button></section></Frame>;
 if(phase==='instructions')return <Frame timer="--:--"><section className="exam-stage"><span className="step">BƯỚC 1 / 2</span><h1>Hướng dẫn làm bài</h1><ul className="instruction-list"><li>Bài có bốn phần và thời gian chung cho toàn bài.</li><li>Bạn có thể xem lại câu trong cùng phần, trừ phần Nghe hiểu.</li><li>Khi chuyển sang phần tiếp theo, bạn không thể quay lại phần trước.</li><li>Đáp án được lưu tự động trong khi làm bài.</li></ul><Alert tone="info">Đây là bài luyện tập không chính thức. Kết quả không tương đương điểm JFT-Basic chính thức.</Alert><div className="stage-actions"><button className="secondary" onClick={()=>router.push('/candidate')}>Thoát</button><button className="primary" onClick={()=>setPhase('audio_check')}>Kiểm tra âm thanh</button></div></section></Frame>;
 if(phase==='audio_check')return <Frame timer="--:--"><section className="exam-stage"><span className="step">BƯỚC 2 / 2</span><h1>Kiểm tra âm thanh</h1><p>Đeo tai nghe và phát đoạn mẫu. Hãy điều chỉnh âm lượng trước khi bắt đầu.</p><div className="audio-check"><audio controls preload="auto" src="/audio/sample-01.wav">Trình duyệt không hỗ trợ âm thanh.</audio><p lang="ja">毎朝八時に会社へ行きます。</p></div><div className="stage-actions"><button className="secondary" onClick={()=>setPhase('instructions')}>Quay lại</button><button className="primary" onClick={()=>void startExam()}>Bắt đầu làm bài</button></div></section></Frame>;
 if(!exam||!session||!q)return null;
 if(phase==='section_intro')return <Frame timer={timer}><section className="exam-stage"><span className="step">PHẦN MỚI</span><h1>{labels[q.section]}</h1><p>{q.section==='listening'?'Câu hỏi chạy lần lượt. Mỗi đoạn âm thanh có thể phát tối đa hai lần và không thể quay lại câu trước.':'Bạn có thể chuyển giữa các câu trong phần này trước khi sang phần tiếp theo.'}</p><button className="primary" onClick={()=>setPhase('testing')}>Bắt đầu phần này</button></section></Frame>;
 if(phase==='section_confirm')return <Frame timer={timer}><section className="exam-stage"><span className="step">HOÀN THÀNH PHẦN</span><h1>Chuyển sang phần tiếp theo?</h1><Alert tone="warning">Sau khi tiếp tục, bạn không thể quay lại phần {labels[q.section]}.</Alert><div className="stage-actions"><button className="secondary" onClick={()=>setPhase('testing')}>Xem lại phần này</button><button className="primary" onClick={enterNextSection}>Tiếp tục</button></div></section></Frame>;
 if(phase==='final_confirm'){const unanswered=exam.questions.length-Object.keys(answers).length;return <Frame timer={timer}><section className="exam-stage"><span className="step">KIỂM TRA CUỐI</span><h1>Nộp bài luyện tập?</h1><div className="info-grid"><div><b>Đã trả lời</b><span>{Object.keys(answers).length}</span></div><div><b>Chưa trả lời</b><span>{unanswered}</span></div><div><b>Thời gian còn lại</b><span>{timer}</span></div></div><div className="stage-actions"><button className="secondary" onClick={()=>setPhase('testing')}>Quay lại</button><button className="primary danger" onClick={()=>void finish()}>Nộp bài</button></div></section></Frame>}
 const position=sectionQuestions.findIndex(z=>z.i===currentIndex)+1,used=plays[q.id]||0;
 return <Frame timer={timer} section={labels[q.section]} progress={`${currentIndex+1}/${exam.questions.length}`}><div className="cbt-layout"><aside className="question-palette" aria-label="Danh sách câu hỏi"><b>{labels[q.section]}</b><div className="qgrid">{sectionQuestions.map(({x,i},n)=><button key={x.id} aria-label={`Câu ${n+1}${answers[x.id]!==undefined?', đã trả lời':''}`} disabled={!rule?.allowBack&&i<currentIndex} className={`qnum ${i===currentIndex?'current':''} ${answers[x.id]!==undefined?'answered':''}`} onClick={()=>go(i)}>{n+1}</button>)}</div><div className={`save-status ${sync}`} role="status">{sync==='saving'?'Đang lưu…':sync==='error'?'Chưa lưu được · kiểm tra mạng':'Đã lưu tự động'}</div></aside><section className="cbt-question"><header><div><span>Câu {position} / {sectionQuestions.length}</span><b>{q.level}</b></div><button className="language-btn" onClick={()=>setLanguage(v=>v==='ja'?'vi':'ja')}>Hướng dẫn: {language==='ja'?'日本語':'Tiếng Việt'}</button></header><div className="cbt-body"><p className="instruction">{language==='vi'?'Chọn một đáp án phù hợp nhất.':q.instruction}</p>{q.type==='audio_choice'&&<div className="listening-player"><audio ref={audioRef} src={q.audioSrc}/><button className="audio-btn" onClick={playAudio} disabled={used>=2} aria-label="Phát âm thanh">▶</button><div><b>{used>=2?'Đã dùng hết lượt phát':'Phát âm thanh'}</b><span>Còn {2-used} / 2 lượt</span></div></div>}<div className="prompt" lang="ja">{q.prompt}</div><fieldset className="choices"><legend className="sr-only">Các lựa chọn</legend>{q.choices.map((choice,i)=><label key={i} className={`choice ${answers[q.id]===i?'selected':''}`}><input type="radio" name={q.id} checked={answers[q.id]===i} onChange={()=>choose(i)}/><span className="choice-index">{i+1}</span><span className="choice-label" lang="ja">{choice}</span></label>)}</fieldset></div><footer><span>Toàn bài: {Object.keys(answers).length}/{exam.questions.length} câu đã trả lời</span><div className="actions"><button className="secondary" disabled={!rule?.allowBack||sectionQuestions[0].i===currentIndex} onClick={()=>go(currentIndex-1)}>Quay lại</button><button className="primary" onClick={advance}>{currentIndex===exam.questions.length-1?'Kiểm tra & nộp':'Tiếp theo'}</button></div></footer></section></div></Frame>;
}
function Frame({timer,section,progress,children}:{timer:string;section?:string;progress?:string;children:React.ReactNode}){return <main className="exam-app"><header className="exam-top"><div className="exam-brand"><b>JFT Practice</b><span>Bài luyện tập không chính thức</span></div>{section&&<div className="exam-context"><span>{section}</span><b>{progress}</b></div>}<div className="exam-timer"><span>Thời gian còn lại</span><b>{timer}</b></div></header><div className="mobile-cbt-note">Để có trải nghiệm gần với CBT nhất, hãy dùng máy tính hoặc máy tính bảng.</div>{children}</main>}
