'use client';
import { useEffect,useMemo,useRef,useState } from 'react';
import { useRouter } from 'next/navigation';
import { candidateApi,CandidateExam,CandidateSession } from '@/lib/api-client';
import { SectionId } from '@/lib/types';
const SESSION_KEY='jft-v42-active-session';
const sectionLabels:Record<SectionId,string>={script_vocabulary:'Script & Vocabulary',conversation_expression:'Conversation & Expression',listening:'Listening Comprehension',reading:'Reading Comprehension'};
type Phase='loading'|'instructions'|'audio_check'|'section_intro'|'testing'|'final_confirm'|'expired'|'error';
export default function ExamClient(){
 const router=useRouter(); const [phase,setPhase]=useState<Phase>('loading'); const [exam,setExam]=useState<CandidateExam|null>(null); const [session,setSession]=useState<CandidateSession|null>(null); const [currentIndex,setCurrentIndex]=useState(0); const [answers,setAnswers]=useState<Record<string,number>>({}); const [remaining,setRemaining]=useState(0); const [language,setLanguage]=useState<'ja'|'vi'>('ja'); const [error,setError]=useState(''); const [sync,setSync]=useState<'idle'|'saving'|'saved'|'error'>('idle'); const audioRef=useRef<HTMLAudioElement|null>(null);
 useEffect(()=>{void bootstrap()},[]);
 useEffect(()=>{if(!session||session.status!=='active')return;const tick=()=>{const left=Math.max(0,new Date(session.expiresAt).getTime()-Date.now());setRemaining(left);if(left===0)void finish()};tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[session]);
 async function bootstrap(){try{let resumeId=localStorage.getItem(SESSION_KEY);if(!resumeId){const mine=await candidateApi.attempts();resumeId=mine.attempts.find(a=>a.status==='active'&&Date.now()<new Date(a.expiresAt).getTime())?.id||null}if(resumeId){try{const r=await candidateApi.resume(resumeId);if(r.session.status==='active'&&Date.now()<new Date(r.session.expiresAt).getTime()){localStorage.setItem(SESSION_KEY,r.session.id);setSession(r.session);setExam(r.exam);setAnswers(r.session.answers||{});setCurrentIndex(r.session.currentIndex||0);setPhase('testing');return}}catch{localStorage.removeItem(SESSION_KEY)}}const latest=await candidateApi.latestExam();if(!latest.version){setError('Chưa có ExamVersion được publish. Hãy vào Admin → Exams và publish một đề.');setPhase('error');return}setPhase('instructions')}catch(e){setError(e instanceof Error?e.message:'Cannot load exam');setPhase('error')}}
 async function startExam(){try{setPhase('loading');const latest=await candidateApi.latestExam();if(!latest.version)throw new Error('No published exam');const r=await candidateApi.createSession(latest.version.id);setSession(r.session);setExam(r.exam);setAnswers(r.session.answers||{});setCurrentIndex(r.session.currentIndex||0);localStorage.setItem(SESSION_KEY,r.session.id);setPhase('section_intro')}catch(e){setError(e instanceof Error?e.message:'Cannot start session');setPhase('error')}}
 const q=exam?.questions[currentIndex]; const sectionConfig=exam&&q?exam.rules.find(r=>r.section===q.section):undefined; const sectionQuestions=useMemo(()=>exam&&q?exam.questions.map((x,i)=>({x,i})).filter(z=>z.x.section===q.section):[],[exam,q]);
 async function persistProgress(index:number,questionId?:string,choice?:number){if(!session)return;try{setSync('saving');await candidateApi.saveAnswer(session.id,questionId,choice,index);setSync('saved')}catch{setSync('error')}}
 function choose(i:number){if(!q)return;setAnswers(a=>({...a,[q.id]:i}));void persistProgress(currentIndex,q.id,i)}
 function go(index:number){if(!exam||!q)return;const next=Math.max(0,Math.min(exam.questions.length-1,index));if(!sectionConfig?.allowBack&&next<currentIndex)return;if(exam.questions[next].section!==q.section)return;setCurrentIndex(next);void persistProgress(next)}
 function next(){if(!exam||!q)return;if(currentIndex===exam.questions.length-1){setPhase('final_confirm');return}const ni=currentIndex+1,nq=exam.questions[ni];setCurrentIndex(ni);void persistProgress(ni);if(nq.section!==q.section)setPhase('section_intro')}
 async function finish(){if(!session)return;try{setPhase('loading');await candidateApi.submit(session.id);localStorage.removeItem(SESSION_KEY);router.push(`/result?sessionId=${encodeURIComponent(session.id)}`)}catch(e){const m=e instanceof Error?e.message:'Submit failed';if(/expired/i.test(m)){setError(m);setPhase('expired')}else{setError(m);setPhase('error')}}}
 function playAudio(){if(q?.audioSrc&&audioRef.current){audioRef.current.currentTime=0;audioRef.current.play().catch(()=>setError('Không phát được audio.'))}}
 const mins=Math.floor(remaining/60000).toString().padStart(2,'0'),secs=Math.floor((remaining%60000)/1000).toString().padStart(2,'0');
 if(phase==='loading')return <Frame timer="--:--"><section className="card stage-card"><h1>Loading…</h1><p>Đang đồng bộ phiên thi với server.</p></section></Frame>;
 if(phase==='expired')return <Frame timer="00:00"><section className="card stage-card"><div className="step">SESSION ENDED</div><h1>Time expired</h1><div className="notice">{error||'Phiên thi đã hết thời gian.'}</div><div className="stage-actions"><span/><button className="primary" onClick={()=>router.replace('/candidate')}>Return to dashboard</button></div></section></Frame>;
 if(phase==='error')return <Frame timer="--:--"><section className="card stage-card"><h1>Cannot continue</h1><div className="notice">{error}</div><div className="stage-actions"><span/><button className="primary" onClick={()=>location.reload()}>Retry</button></div></section></Frame>;
 if(phase==='instructions')return <Frame timer="--:--"><section className="card stage-card"><div className="step">STEP 1 / 3</div><h1>Test Instructions</h1><p>V4.2 gắn CandidateSession với tài khoản. Refresh hoặc đăng nhập lại có thể resume active session từ backend.</p><div className="notice">Đáp án đúng không được gửi xuống browser; chấm điểm diễn ra trên server.</div><div className="stage-actions"><span/><button className="primary" onClick={()=>setPhase('audio_check')}>Continue</button></div></section></Frame>;
 if(phase==='audio_check')return <Frame timer="--:--"><section className="card stage-card"><div className="step">STEP 2 / 3</div><h1>Audio Check</h1><p>Kiểm tra tai nghe trước khi bắt đầu. Timer server chỉ được tạo khi bấm Start Test.</p><div className="audio-box"><button className="audio-btn">▶</button><div>Audio check placeholder</div></div><div className="stage-actions"><button className="secondary" onClick={()=>setPhase('instructions')}>Back</button><button className="primary" onClick={()=>void startExam()}>Start Test</button></div></section></Frame>;
 if(!exam||!session||!q)return null;
 if(phase==='section_intro')return <Frame timer={`${mins}:${secs}`}><section className="card stage-card"><div className="step">SECTION</div><h1>{sectionLabels[q.section]}</h1><p>{q.section==='listening'?'Listening chạy tuần tự và không cho quay lại câu trước.':'Bạn có thể chuyển giữa các câu trong cùng section.'}</p><div className="stage-actions"><span/><button className="primary" onClick={()=>setPhase('testing')}>Begin Section</button></div></section></Frame>;
 if(phase==='final_confirm'){const unanswered=exam.questions.length-Object.keys(answers).length;return <Frame timer={`${mins}:${secs}`}><section className="card stage-card"><div className="step">FINAL</div><h1>End Test?</h1><div className="info-grid"><div><b>Answered</b><span>{Object.keys(answers).length}</span></div><div><b>Unanswered</b><span>{unanswered}</span></div><div><b>Remaining</b><span>{mins}:{secs}</span></div></div><div className="stage-actions"><button className="secondary" onClick={()=>setPhase('testing')}>Return</button><button className="primary danger" onClick={()=>void finish()}>Submit Test</button></div></section></Frame>}
 return <Frame timer={`${mins}:${secs}`}><div className="page exam-layout"><aside className="card sidebar"><div className="section-name">{sectionLabels[q.section]}</div><div className="qgrid">{sectionQuestions.map(({x,i},n)=><button key={x.id} disabled={!sectionConfig?.allowBack&&i<currentIndex} className={`qnum ${i===currentIndex?'current':''} ${answers[x.id]!==undefined?'answered':''}`} onClick={()=>go(i)}>{n+1}</button>)}</div><div className="legend"><span>{sync==='saving'?'Saving…':sync==='error'?'Save error':'Server synced'}</span></div></aside><section className="card exam-card"><div className="exam-head"><div><strong>{sectionLabels[q.section]}</strong><small>{q.level}</small></div><div className="head-actions"><button className="language-btn" onClick={()=>setLanguage(v=>v==='ja'?'vi':'ja')}>Your Language: {language==='ja'?'OFF':'VI'}</button><span>Question {sectionQuestions.findIndex(z=>z.i===currentIndex)+1} / {sectionQuestions.length}</span></div></div><div className="exam-body"><div className="instruction">{language==='vi'?'Chọn một đáp án phù hợp nhất.':q.instruction}</div>{q.type==='audio_choice'&&<div className="audio-box"><audio ref={audioRef} src={q.audioSrc}/><button className="audio-btn" onClick={playAudio}>▶</button><div>Play Audio</div></div>}<div className="prompt" style={{whiteSpace:'pre-line'}}>{q.prompt}</div><div className="choices">{q.choices.map((choice,i)=><label key={i} className={`choice ${answers[q.id]===i?'selected':''}`}><input type="radio" checked={answers[q.id]===i} onChange={()=>choose(i)}/><span className="choice-label">{i+1}. {choice}</span></label>)}</div></div><div className="exam-foot"><span className="progress">Answered {Object.keys(answers).length} / {exam.questions.length}</span><div className="actions"><button className="secondary" disabled={!sectionConfig?.allowBack||sectionQuestions[0].i===currentIndex} onClick={()=>go(currentIndex-1)}>Back</button><button className="primary" onClick={next}>{currentIndex===exam.questions.length-1?'Review & End':'Next'}</button></div></div></section></div></Frame>;
}
function Frame({timer,children}:{timer:string,children:React.ReactNode}){return <main className="shell"><header className="topbar"><div className="brand">JFT SIMULATOR<small>V5.1.2 QA-hardened CBT</small></div><div><div className="timer-label">TIME REMAINING</div><div className="timer">{timer}</div></div></header>{children}</main>}
