import type { ReactNode } from 'react';
export function PageHeader({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <div className="page-header"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div className="page-actions">{actions}</div>}</div>}
export function Card({children,className='',title,action}:{children:ReactNode;className?:string;title?:string;action?:ReactNode}){return <section className={`ui-card ${className}`}>{(title||action)&&<header className="section-header"><h2>{title}</h2>{action}</header>}{children}</section>}
export function Alert({children,tone='info',title}:{children:ReactNode;tone?:'info'|'success'|'warning'|'danger';title?:string}){return <div className={`ui-alert ${tone}`} role={tone==='danger'?'alert':'status'}>{title&&<strong>{title}</strong>}<div>{children}</div></div>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'success'|'warning'|'danger'|'info'}){return <span className={`ui-badge ${tone}`}>{children}</span>}
export function EmptyState({title,description,action}:{title:string;description:string;action?:ReactNode}){return <div className="empty-state"><div className="empty-mark" aria-hidden="true">—</div><h3>{title}</h3><p>{description}</p>{action}</div>}
export function Skeleton({lines=3}:{lines?:number}){return <div className="skeleton" aria-label="Đang tải" role="status">{Array.from({length:lines},(_,i)=><span key={i}/>)}</div>}
export function Progress({value,label}:{value:number;label?:string}){const safe=Math.max(0,Math.min(100,value));return <div className="ui-progress"><div className="progress-meta"><span>{label}</span><b>{Math.round(safe)}%</b></div><div className="progress-track"><span style={{width:`${safe}%`}}/></div></div>}
export function StatCard({label,value,note}:{label:string;value:string|number;note?:string}){return <div className="stat-card"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
