'use client';
import { useEffect,useState } from 'react';
import { adminApi } from '@/lib/api-client';
import { ExamDraft,ExamVersion,QuestionRecord } from '@/lib/admin-types';
import { SectionId } from '@/lib/types';
import { ADMIN_SECTION_LABELS } from '@/lib/admin-ui';
import type { A1MvpReleaseReport } from '@/lib/server/a1-mvp-release';

export default function ExamBuilderClient(){
  const [draft,setDraft]=useState<ExamDraft|null>(null),[bank,setBank]=useState<QuestionRecord[]>([]),[versions,setVersions]=useState<ExamVersion[]>([]),[releaseReport,setReleaseReport]=useState<A1MvpReleaseReport|null>(null),[publishedPack,setPublishedPack]=useState<string[]>([]),[message,setMessage]=useState<{kind:'ok'|'error';text:string}|null>(null),[saving,setSaving]=useState(false),[releasing,setReleasing]=useState(false);
  useEffect(()=>{void Promise.all([adminApi.exam(),adminApi.questions()]).then(([exam,questions])=>{setDraft(exam.draft);setVersions(exam.versions);setBank(questions.questions)}).catch(error=>setMessage({kind:'error',text:error.message}));void adminApi.a1MvpRelease().then(release=>{setReleaseReport(release.report);setPublishedPack(release.publishedVersionIds)}).catch(error=>setMessage({kind:'error',text:`Gói A1 chưa sẵn sàng: ${error.message}`}))},[]);
  if(!draft)return <section className="admin-panel"><p>Đang tải trình tạo đề…</p></section>;
  function updateCount(section:SectionId,count:number){setDraft(current=>current?{...current,status:'draft',rules:current.rules.map(rule=>rule.section===section?{...rule,count:Math.max(0,count)}:rule)}:current)}
  function updateLevels(section:SectionId,value:string){const levels=value==='ALL'?['A1','A2.1','A2.2'] as const:[value as 'A1'|'A2.1'|'A2.2'];setDraft(current=>current?{...current,status:'draft',rules:current.rules.map(rule=>rule.section===section?{...rule,levels:[...levels]}:rule)}:current)}
  async function save(){if(!draft)return;try{setSaving(true);const result=await adminApi.saveExam(draft);setDraft(result.draft);setMessage({kind:'ok',text:'Đã lưu bản nháp vào hệ thống.'})}catch(error){setMessage({kind:'error',text:error instanceof Error?error.message:'Lưu thất bại.'})}finally{setSaving(false)}}
  async function publish(){if(!draft)return;try{await adminApi.saveExam(draft);const result=await adminApi.publishExam(draft.id);setVersions(current=>[result.version,...current]);setDraft(current=>current?{...current,status:'published'}:current);setMessage({kind:'ok',text:`Đã phát hành ${result.version.id} với ${result.version.questions.length} ảnh chụp câu hỏi bất biến.`})}catch(error){setMessage({kind:'error',text:error instanceof Error?error.message:'Phát hành thất bại.'})}}
  async function publishA1Pack(){try{setReleasing(true);const result=await adminApi.publishA1MvpRelease();setReleaseReport(result.report);setPublishedPack([...result.published,...result.skipped]);setMessage({kind:'ok',text:result.published.length?`Đã phát hành ${result.published.length} đề A1; ${result.skipped.length} đề đã tồn tại được giữ nguyên.`:'Cả 5 đề A1 đã tồn tại; không thay đổi snapshot.'})}catch(error){setMessage({kind:'error',text:error instanceof Error?error.message:'Không thể phát hành gói A1.'})}finally{setReleasing(false)}}
  return <>
    <div className="admin-title"><div><span className="eyebrow">LẮP RÁP ĐỀ THI</span><h1>Trình tạo đề</h1><p>Bản nháp và phiên bản đã phát hành được lưu qua Repository của backend.</p></div><div className="home-actions"><button className="secondary" onClick={()=>void save()}>{saving?'Đang lưu…':'Lưu bản nháp'}</button><button className="primary" onClick={()=>void publish()}>Phát hành phiên bản</button></div></div>
    {message&&<div className={`admin-alert ${message.kind}`}>{message.text}</div>}
    <section className="admin-panel" data-testid="a1-mvp-release-pack"><div className="panel-head"><div><h2>Gói phát hành A1 MVP</h2><p>5 đề mini, mỗi đề 8 câu; chỉ dùng 17 câu A1 đã duyệt và snapshot bất biến.</p></div><span className={`readiness-pill ${releaseReport?'ready':'blocked'}`}>{releaseReport?'Sẵn sàng':'Chưa sẵn sàng'}</span></div>{releaseReport&&<><div className="metric-grid three"><div className="metric"><span>Số đề</span><strong>{releaseReport.examCount}</strong></div><div className="metric"><span>Tái sử dụng tối đa</span><strong>{releaseReport.maxQuestionReuse} lần</strong></div><div className="metric"><span>Overlap tối đa</span><strong>{Math.round(releaseReport.maxPairwiseOverlapRatio*100)}%</strong></div></div><p className="helper">Blueprint {releaseReport.blueprintVersion}. Giới hạn overlap 37,5% là quyết định MVP do kho A1 hiện chỉ có 17 câu, không phải quy tắc JFT chính thức.</p><div className="home-actions"><button className="primary" disabled={releasing||publishedPack.length===releaseReport.examCount} onClick={()=>void publishA1Pack()}>{releasing?'Đang phát hành…':publishedPack.length===releaseReport.examCount?'Đã phát hành đủ 5 đề':'Phát hành 5 đề A1'}</button></div></>}
    </section>
    <section className="admin-panel builder-head"><div><label>Tên đề thi</label><input value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value,status:'draft'})}/></div><div><label>Thời lượng</label><div className="input-suffix"><input type="number" value={draft.durationMinutes} onChange={event=>setDraft({...draft,durationMinutes:Number(event.target.value),status:'draft'})}/><span>phút</span></div></div><div><label>ID đề thi</label><code>{draft.id}</code></div></section>
    <section className="admin-panel"><div className="panel-head"><h2>Cấu trúc đề</h2><span className="badge">Chỉ dùng câu đã duyệt</span></div><div className="rule-list">{draft.rules.map((rule,index)=>{const eligible=bank.filter(question=>question.status==='approved'&&question.section===rule.section&&rule.levels.includes(question.level)).length,enough=eligible>=rule.count,levelValue=rule.levels.length===1?rule.levels[0]:'ALL';return <div className="rule-card" key={rule.section}><div className="rule-index">{index+1}</div><div className="rule-name"><b>{ADMIN_SECTION_LABELS[rule.section]}</b><small>{rule.allowBack?'Cho phép quay lại':'Làm tuần tự, không quay lại'}</small></div><div className="level-edit"><label>Cấp độ</label><select aria-label={`Cấp độ ${ADMIN_SECTION_LABELS[rule.section]}`} value={levelValue} onChange={event=>updateLevels(rule.section,event.target.value)}><option value="A1">A1</option><option value="A2.1">A2.1</option><option value="A2.2">A2.2</option><option value="ALL">Tất cả</option></select></div><div className="pool"><span>Kho phù hợp</span><b>{eligible}</b></div><div className="count-edit"><label>Số câu</label><input type="number" min="0" value={rule.count} onChange={event=>updateCount(rule.section,Number(event.target.value))}/></div><span className={`readiness-pill ${enough?'ready':'blocked'}`}>{enough?'Sẵn sàng':'Chưa đủ câu'}</span></div>})}</div></section>
    <section className="admin-grid-2"><div className="admin-panel"><div className="panel-head"><h2>Điều kiện phát hành</h2></div><ul className="contract"><li>Chỉ câu hỏi <b>đã duyệt</b> mới được sử dụng.</li><li>Phiên bản câu hỏi được đóng băng khi phát hành.</li><li>Học viên không nhận đáp án hoặc lời giải trong lúc thi.</li><li>Máy chủ chấm điểm theo ExamVersion đã đóng băng.</li></ul></div><div className="admin-panel"><div className="panel-head"><h2>Phiên bản đã tạo</h2><span>{versions.length}</span></div>{versions.length===0?<p className="empty">Chưa có phiên bản nào được phát hành.</p>:<div className="version-list">{versions.map(version=><div key={version.id}><b>{version.id}</b><span>{version.questions.length} câu</span><small>{new Date(version.publishedAt).toLocaleString('vi-VN')}</small></div>)}</div>}</div></section>
  </>;
}
