'use client';
import { useEffect,useMemo,useState } from 'react';
import { adminApi } from '@/lib/api-client';
import { ExamDraft,ExamVersion,QuestionRecord } from '@/lib/admin-types';
import { SectionId } from '@/lib/types';
const labels:Record<SectionId,string>={script_vocabulary:'Script & Vocabulary',conversation_expression:'Conversation & Expression',listening:'Listening Comprehension',reading:'Reading Comprehension'};
export default function ExamBuilderClient(){const [draft,setDraft]=useState<ExamDraft|null>(null),[bank,setBank]=useState<QuestionRecord[]>([]),[versions,setVersions]=useState<ExamVersion[]>([]),[message,setMessage]=useState<{kind:'ok'|'error';text:string}|null>(null),[saving,setSaving]=useState(false);
 useEffect(()=>{void Promise.all([adminApi.exam(),adminApi.questions()]).then(([e,q])=>{setDraft(e.draft);setVersions(e.versions);setBank(q.questions)}).catch(e=>setMessage({kind:'error',text:e.message}))},[]);
 const pools=useMemo(()=>Object.fromEntries((Object.keys(labels) as SectionId[]).map(id=>[id,bank.filter(q=>q.status==='approved'&&q.section===id).length])) as Record<SectionId,number>,[bank]);
 if(!draft)return <section className="admin-panel"><p>Loading exam builder…</p></section>;
 function updateCount(section:SectionId,count:number){setDraft(d=>d?{...d,status:'draft',rules:d.rules.map(r=>r.section===section?{...r,count:Math.max(0,count)}:r)}:d)}
 async function save(){if(!draft)return;try{setSaving(true);const r=await adminApi.saveExam(draft);setDraft(r.draft);setMessage({kind:'ok',text:'Draft saved to backend.'})}catch(e){setMessage({kind:'error',text:e instanceof Error?e.message:'Save failed'})}finally{setSaving(false)}}
 async function publish(){if(!draft)return;try{await adminApi.saveExam(draft);const r=await adminApi.publishExam(draft.id);setVersions(v=>[r.version,...v]);setDraft(d=>d?{...d,status:'published'}:d);setMessage({kind:'ok',text:`Published ${r.version.id}: ${r.version.questions.length} immutable snapshots.`})}catch(e){setMessage({kind:'error',text:e instanceof Error?e.message:'Publish failed'})}}
 return <><div className="admin-title"><div><span className="eyebrow">ASSEMBLY · API</span><h1>Exam Builder</h1><p>Draft và published versions giờ được lưu bởi backend Repository.</p></div><div className="home-actions"><button className="secondary" onClick={()=>void save()}>{saving?'Saving…':'Save draft'}</button><button className="primary" onClick={()=>void publish()}>Publish version</button></div></div>{message&&<div className={`admin-alert ${message.kind}`}>{message.text}</div>}<section className="admin-panel builder-head"><div><label>Exam title</label><input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value,status:'draft'})}/></div><div><label>Duration</label><div className="input-suffix"><input type="number" value={draft.durationMinutes} onChange={e=>setDraft({...draft,durationMinutes:Number(e.target.value),status:'draft'})}/><span>min</span></div></div><div><label>Exam ID</label><code>{draft.id}</code></div></section><section className="admin-panel"><div className="panel-head"><h2>Section blueprint</h2><span className="badge">Approved pool only</span></div><div className="rule-list">{draft.rules.map((r,i)=>{const enough=pools[r.section]>=r.count;return <div className="rule-card" key={r.section}><div className="rule-index">{i+1}</div><div className="rule-name"><b>{labels[r.section]}</b><small>{r.allowBack?'Back navigation allowed':'Sequential / no back'}</small></div><div className="pool"><span>Pool</span><b>{pools[r.section]}</b></div><div className="count-edit"><label>Questions</label><input type="number" min="0" value={r.count} onChange={e=>updateCount(r.section,Number(e.target.value))}/></div><span className={`readiness-pill ${enough?'ready':'blocked'}`}>{enough?'Ready':'Not enough'}</span></div>})}</div></section><section className="admin-grid-2"><div className="admin-panel"><div className="panel-head"><h2>Publish contract</h2></div><ul className="contract"><li>Only <b>approved</b> questions are eligible.</li><li>Question version is captured at publish time.</li><li>Candidate never receives answer/explanation.</li><li>Server scores against frozen ExamVersion.</li></ul></div><div className="admin-panel"><div className="panel-head"><h2>Generated versions</h2><span>{versions.length}</span></div>{versions.length===0?<p className="empty">No published versions yet.</p>:<div className="version-list">{versions.map(v=><div key={v.id}><b>{v.id}</b><span>{v.questions.length} questions</span><small>{new Date(v.publishedAt).toLocaleString()}</small></div>)}</div>}</div></section></>}
