'use client';
import { useEffect,useMemo,useState } from 'react';
import { adminApi } from '@/lib/api-client';
import { ExamDraft,ExamVersion,QuestionRecord } from '@/lib/admin-types';
import { SectionId } from '@/lib/types';
import { ADMIN_SECTION_LABELS } from '@/lib/admin-ui';

export default function ExamBuilderClient(){
  const [draft,setDraft]=useState<ExamDraft|null>(null),[bank,setBank]=useState<QuestionRecord[]>([]),[versions,setVersions]=useState<ExamVersion[]>([]),[message,setMessage]=useState<{kind:'ok'|'error';text:string}|null>(null),[saving,setSaving]=useState(false);
  useEffect(()=>{void Promise.all([adminApi.exam(),adminApi.questions()]).then(([exam,questions])=>{setDraft(exam.draft);setVersions(exam.versions);setBank(questions.questions)}).catch(error=>setMessage({kind:'error',text:error.message}))},[]);
  const pools=useMemo(()=>Object.fromEntries((Object.keys(ADMIN_SECTION_LABELS) as SectionId[]).map(id=>[id,bank.filter(question=>question.status==='approved'&&question.section===id).length])) as Record<SectionId,number>,[bank]);
  if(!draft)return <section className="admin-panel"><p>Đang tải trình tạo đề…</p></section>;
  function updateCount(section:SectionId,count:number){setDraft(current=>current?{...current,status:'draft',rules:current.rules.map(rule=>rule.section===section?{...rule,count:Math.max(0,count)}:rule)}:current)}
  async function save(){if(!draft)return;try{setSaving(true);const result=await adminApi.saveExam(draft);setDraft(result.draft);setMessage({kind:'ok',text:'Đã lưu bản nháp vào hệ thống.'})}catch(error){setMessage({kind:'error',text:error instanceof Error?error.message:'Lưu thất bại.'})}finally{setSaving(false)}}
  async function publish(){if(!draft)return;try{await adminApi.saveExam(draft);const result=await adminApi.publishExam(draft.id);setVersions(current=>[result.version,...current]);setDraft(current=>current?{...current,status:'published'}:current);setMessage({kind:'ok',text:`Đã phát hành ${result.version.id} với ${result.version.questions.length} ảnh chụp câu hỏi bất biến.`})}catch(error){setMessage({kind:'error',text:error instanceof Error?error.message:'Phát hành thất bại.'})}}
  return <>
    <div className="admin-title"><div><span className="eyebrow">LẮP RÁP ĐỀ THI</span><h1>Trình tạo đề</h1><p>Bản nháp và phiên bản đã phát hành được lưu qua Repository của backend.</p></div><div className="home-actions"><button className="secondary" onClick={()=>void save()}>{saving?'Đang lưu…':'Lưu bản nháp'}</button><button className="primary" onClick={()=>void publish()}>Phát hành phiên bản</button></div></div>
    {message&&<div className={`admin-alert ${message.kind}`}>{message.text}</div>}
    <section className="admin-panel builder-head"><div><label>Tên đề thi</label><input value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value,status:'draft'})}/></div><div><label>Thời lượng</label><div className="input-suffix"><input type="number" value={draft.durationMinutes} onChange={event=>setDraft({...draft,durationMinutes:Number(event.target.value),status:'draft'})}/><span>phút</span></div></div><div><label>ID đề thi</label><code>{draft.id}</code></div></section>
    <section className="admin-panel"><div className="panel-head"><h2>Cấu trúc đề</h2><span className="badge">Chỉ dùng câu đã duyệt</span></div><div className="rule-list">{draft.rules.map((rule,index)=>{const enough=pools[rule.section]>=rule.count;return <div className="rule-card" key={rule.section}><div className="rule-index">{index+1}</div><div className="rule-name"><b>{ADMIN_SECTION_LABELS[rule.section]}</b><small>{rule.allowBack?'Cho phép quay lại':'Làm tuần tự, không quay lại'}</small></div><div className="pool"><span>Kho câu</span><b>{pools[rule.section]}</b></div><div className="count-edit"><label>Số câu</label><input type="number" min="0" value={rule.count} onChange={event=>updateCount(rule.section,Number(event.target.value))}/></div><span className={`readiness-pill ${enough?'ready':'blocked'}`}>{enough?'Sẵn sàng':'Chưa đủ câu'}</span></div>})}</div></section>
    <section className="admin-grid-2"><div className="admin-panel"><div className="panel-head"><h2>Điều kiện phát hành</h2></div><ul className="contract"><li>Chỉ câu hỏi <b>đã duyệt</b> mới được sử dụng.</li><li>Phiên bản câu hỏi được đóng băng khi phát hành.</li><li>Học viên không nhận đáp án hoặc lời giải trong lúc thi.</li><li>Máy chủ chấm điểm theo ExamVersion đã đóng băng.</li></ul></div><div className="admin-panel"><div className="panel-head"><h2>Phiên bản đã tạo</h2><span>{versions.length}</span></div>{versions.length===0?<p className="empty">Chưa có phiên bản nào được phát hành.</p>:<div className="version-list">{versions.map(version=><div key={version.id}><b>{version.id}</b><span>{version.questions.length} câu</span><small>{new Date(version.publishedAt).toLocaleString('vi-VN')}</small></div>)}</div>}</div></section>
  </>;
}
