'use client';
import { useEffect,useMemo,useState } from 'react';
import Link from 'next/link';
import { adminApi } from '@/lib/api-client';
import { QuestionRecord,QuestionStatus } from '@/lib/admin-types';
import { SectionId } from '@/lib/types';
import { ADMIN_SECTION_LABELS,ADMIN_STATUS_LABELS } from '@/lib/admin-ui';
import { EmptyState,Skeleton } from '@/components/ui';

const PAGE_SIZE=50;

export default function QuestionBankClient(){
  const [rows,setRows]=useState<QuestionRecord[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState<'all'|QuestionStatus>('all'),[section,setSection]=useState<'all'|SectionId>('all'),[level,setLevel]=useState('all'),[selected,setSelected]=useState<QuestionRecord|null>(null),[loading,setLoading]=useState(true),[importing,setImporting]=useState(false),[page,setPage]=useState(1),[message,setMessage]=useState(''),[error,setError]=useState('');
  const load=async()=>{const result=await adminApi.questions();setRows(result.questions)};
  useEffect(()=>{void load().catch(()=>setError('Không thể tải Ngân hàng câu hỏi.')).finally(()=>setLoading(false))},[]);
  useEffect(()=>setPage(1),[query,status,section,level]);
  const filtered=useMemo(()=>rows.filter(question=>(status==='all'||question.status===status)&&(section==='all'||question.section===section)&&(level==='all'||question.level===level)&&`${question.id} ${question.prompt} ${question.tags.join(' ')}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())),[rows,query,status,section,level]);
  const pageCount=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));
  const visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
  async function setState(next:QuestionStatus){if(!selected)return;setError('');try{const result=await adminApi.saveQuestion({...selected,status:next,version:selected.version+1,updatedAt:new Date().toISOString()});setRows(current=>current.map(question=>question.id===result.question.id?result.question:question));setSelected(result.question);setMessage(`Đã chuyển câu hỏi sang trạng thái “${ADMIN_STATUS_LABELS[next]}”.`)}catch{setError('Không thể cập nhật câu hỏi này.')}}
  async function importProduction(){setImporting(true);setError('');setMessage('');try{const result=await adminApi.importProductionQuestions();await load();setMessage(`Đã nạp ${result.imported.toLocaleString('vi-VN')} câu thuộc batch ${result.batch}. Tất cả câu chưa duyệt vẫn ở hàng chờ kiểm tra.`)}catch(error){setError(error instanceof Error?error.message:'Không thể nạp bộ câu hỏi.')}finally{setImporting(false)}}
  return <>
    <div className="admin-title"><div><span className="eyebrow">THƯ VIỆN NỘI DUNG</span><h1>Ngân hàng câu hỏi</h1><p>Tìm kiếm, lọc và duyệt nội dung luyện thi có kiểm soát.</p></div><div className="home-actions"><button className="secondary" disabled={importing} onClick={()=>void importProduction()}>{importing?'Đang nạp 2.100 câu…':'Nạp bộ 2.100 câu chờ duyệt'}</button><Link className="primary admin-cta" href="/admin/factory">Sinh câu hỏi</Link></div></div>
    {error&&<div className="admin-alert error">{error}</div>}{message&&<div className="admin-alert ok">{message}</div>}
    <section className="metric-grid three"><div className="metric"><span>Tổng câu hỏi</span><strong>{rows.length.toLocaleString('vi-VN')}</strong></div><div className="metric"><span>Đã duyệt</span><strong>{rows.filter(question=>question.status==='approved').length.toLocaleString('vi-VN')}</strong></div><div className="metric"><span>Chờ duyệt</span><strong>{rows.filter(question=>question.status==='review').length.toLocaleString('vi-VN')}</strong></div></section>
    <div className="toolbar" aria-label="Bộ lọc câu hỏi"><input aria-label="Tìm câu hỏi" placeholder="Tìm nội dung, ID hoặc thẻ…" value={query} onChange={event=>setQuery(event.target.value)}/><select aria-label="Cấp độ" value={level} onChange={event=>setLevel(event.target.value)}><option value="all">Tất cả cấp độ</option><option>A1</option><option>A2.1</option><option>A2.2</option></select><select aria-label="Phần thi" value={section} onChange={event=>setSection(event.target.value as typeof section)}><option value="all">Tất cả phần thi</option>{Object.entries(ADMIN_SECTION_LABELS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><select aria-label="Trạng thái" value={status} onChange={event=>setStatus(event.target.value as typeof status)}><option value="all">Tất cả trạng thái</option>{(Object.keys(ADMIN_STATUS_LABELS) as QuestionStatus[]).map(value=><option key={value} value={value}>{ADMIN_STATUS_LABELS[value]}</option>)}</select></div>
    {loading?<section className="admin-panel"><Skeleton lines={8}/></section>:visible.length?<><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>ID</th><th>Phần thi</th><th>Cấp độ</th><th>Câu hỏi</th><th>Nguồn</th><th>Trạng thái</th></tr></thead><tbody>{visible.map(question=><tr key={question.id} onClick={()=>setSelected(question)} tabIndex={0} onKeyDown={event=>{if(event.key==='Enter')setSelected(question)}}><td className="mono">{question.id}</td><td>{ADMIN_SECTION_LABELS[question.section]}</td><td>{question.level}</td><td className="prompt-cell" lang="ja">{question.prompt}</td><td>{question.source}</td><td><span className={`badge ${question.status}`}>{ADMIN_STATUS_LABELS[question.status]}</span></td></tr>)}</tbody></table></div><div className="pagination" aria-label="Phân trang"><button className="secondary" disabled={page===1} onClick={()=>setPage(current=>Math.max(1,current-1))}>← Trang trước</button><span>Trang {page}/{pageCount} · {filtered.length.toLocaleString('vi-VN')} câu</span><button className="secondary" disabled={page===pageCount} onClick={()=>setPage(current=>Math.min(pageCount,current+1))}>Trang sau →</button></div></>:<section className="admin-panel"><EmptyState title="Không có câu hỏi phù hợp" description="Hãy điều chỉnh bộ lọc hoặc sinh nội dung cho phần chương trình còn thiếu."/></section>}
    {selected&&<div className="drawer-backdrop" onClick={()=>setSelected(null)} role="presentation"><aside className="drawer" role="dialog" aria-modal="true" aria-labelledby="question-title" onClick={event=>event.stopPropagation()}><button className="drawer-close" aria-label="Đóng chi tiết câu hỏi" onClick={()=>setSelected(null)}>×</button><span className="eyebrow">CHI TIẾT CÂU HỎI</span><h2 id="question-title">{selected.id} <small>phiên bản {selected.version}</small></h2><div className="meta-row"><span>{ADMIN_SECTION_LABELS[selected.section]}</span><span>{selected.level}</span><span>{selected.source}</span></div><p className="preview-instruction" lang="ja">{selected.instruction}</p><div className="preview-prompt" lang="ja">{selected.prompt}</div><ol className="preview-choices">{selected.choices.map((choice,index)=><li key={index} className={index===selected.answer?'correct':''} lang="ja">{choice}{index===selected.answer&&<b> ✓ Đáp án đúng</b>}</li>)}</ol><div className="explain"><b>Giải thích</b><p>{selected.explanationVi}</p></div><details><summary>Siêu dữ liệu và thẻ</summary><p>{selected.tags.join(' · ')||'Không có thẻ'}</p></details><div className="drawer-actions"><button className="secondary" onClick={()=>void setState('review')}>Chuyển về chờ duyệt</button><button className="primary" onClick={()=>void setState('approved')}>Duyệt câu hỏi</button></div></aside></div>}
  </>;
}
