'use client';
import { useEffect,useMemo,useState } from 'react';
import { adminApi } from '@/lib/api-client';
import { QuestionRecord,QuestionStatus } from '@/lib/admin-types';
import { SectionId } from '@/lib/types';
const sectionName:Record<SectionId,string>={script_vocabulary:'Script & Vocabulary',conversation_expression:'Conversation',listening:'Listening',reading:'Reading'};
export default function QuestionBankClient(){
 const [rows,setRows]=useState<QuestionRecord[]>([]),[query,setQuery]=useState('');const [status,setStatus]=useState<'all'|QuestionStatus>('all');const [section,setSection]=useState<'all'|SectionId>('all');const [selected,setSelected]=useState<QuestionRecord|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [mode,setMode]=useState('');
 async function reload(){try{setLoading(true);const r=await adminApi.questions();setRows(r.questions);setMode(r.mode);setError('')}catch(e){setError(e instanceof Error?e.message:'Load failed')}finally{setLoading(false)}}
 useEffect(()=>{void reload()},[]);
 const filtered=useMemo(()=>rows.filter(q=>(status==='all'||q.status===status)&&(section==='all'||q.section===section)&&(`${q.id} ${q.prompt} ${q.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()))),[rows,query,status,section]);
 async function persist(q:QuestionRecord){try{const r=await adminApi.saveQuestion(q);setRows(x=>x.map(v=>v.id===q.id?r.question:v));setSelected(r.question);setError('')}catch(e){setError(e instanceof Error?e.message:'Save failed')}}
 async function setState(next:QuestionStatus){if(!selected)return;await persist({...selected,status:next,version:selected.version+1,updatedAt:new Date().toISOString()})}
 async function addDemo(){const n=rows.length+1,now=new Date().toISOString();const item:QuestionRecord={id:`NEW-${String(n).padStart(3,'0')}`,section:'script_vocabulary',type:'choice',level:'A2.1',instruction:'もっとも いい ものを ひとつ えらんで ください。',prompt:'新しい問題を入力してください。',choices:['選択肢1','選択肢2','選択肢3','選択肢4'],answer:0,explanationVi:'Thêm giải thích tại đây.',tags:['draft'],version:1,status:'draft',source:'original',createdAt:now,updatedAt:now};try{const r=await adminApi.saveQuestion(item);setRows(x=>[r.question,...x]);setSelected(r.question)}catch(e){setError(e instanceof Error?e.message:'Create failed')}}
 return <><div className="admin-title"><div><span className="eyebrow">CONTENT · API {mode||'...'}</span><h1>Question Bank</h1><p>V4.2 đọc/ghi trực tiếp qua /api/v1/questions. localStorage không còn là source of truth.</p></div><button className="primary" onClick={addDemo}>+ New question</button></div>{error&&<div className="admin-alert error">{error}</div>}<div className="toolbar"><input placeholder="Search id, prompt, tags…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={section} onChange={e=>setSection(e.target.value as typeof section)}><option value="all">All sections</option>{Object.entries(sectionName).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">All status</option>{['draft','review','approved','archived'].map(v=><option key={v}>{v}</option>)}</select></div>{loading?<section className="admin-panel"><p>Loading question bank…</p></section>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>ID</th><th>Section</th><th>Level</th><th>Prompt</th><th>Version</th><th>Status</th></tr></thead><tbody>{filtered.map(q=><tr key={q.id} onClick={()=>setSelected(q)}><td className="mono">{q.id}</td><td>{sectionName[q.section]}</td><td>{q.level}</td><td className="prompt-cell">{q.prompt}</td><td>v{q.version}</td><td><span className={`badge ${q.status}`}>{q.status}</span></td></tr>)}</tbody></table></div>}{selected&&<div className="drawer-backdrop" onClick={()=>setSelected(null)}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><span className="eyebrow">SERVER QUESTION</span><h2>{selected.id} <small>v{selected.version}</small></h2><div className="meta-row"><span>{sectionName[selected.section]}</span><span>{selected.level}</span><span>{selected.type}</span></div><p className="preview-instruction">{selected.instruction}</p><div className="preview-prompt">{selected.prompt}</div><ol className="preview-choices">{selected.choices.map((c,i)=><li key={i} className={i===selected.answer?'correct':''}>{c}{i===selected.answer&&<b> ✓</b>}</li>)}</ol><div className="explain"><b>Giải thích</b><p>{selected.explanationVi}</p></div><div className="drawer-actions"><button className="secondary" onClick={()=>void setState('review')}>Send to review</button><button className="primary" onClick={()=>void setState('approved')}>Approve</button></div></aside></div>}</>;
}
