'use client';
import { useEffect,useState } from 'react';
import { adminApi } from '@/lib/api-client';
import type { KnowledgeUnit,QuestionPlan,QuestionProvenance,SourceChunk,SourceDocument } from '@/lib/server/source-domain';
type Detail={source:SourceDocument;chunks:SourceChunk[];knowledgeUnits:KnowledgeUnit[];plans:QuestionPlan[];provenance:QuestionProvenance[]};
export default function SourcesClient(){
 const [sources,setSources]=useState<SourceDocument[]>([]),[detail,setDetail]=useState<Detail|null>(null),[title,setTitle]=useState('Hospital reception pilot'),[content,setContent]=useState('病院で受付をします。\n\n受付で保険証を出します。\n\nどこが痛いか簡単に説明します。\n\n診察が終わったら会計をします。'),[count,setCount]=useState(4),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async(id?:string)=>{const x=await adminApi.sources();setSources(x.sources);if(id)setDetail(await adminApi.source(id));};useEffect(()=>{load().catch(show)},[]);function show(e:unknown){setMessage(e instanceof Error?e.message:String(e));}
 async function act(fn:()=>Promise<unknown>,id?:string){setBusy(true);setMessage('');try{await fn();await load(id||detail?.source.id);}catch(e){show(e)}finally{setBusy(false)}}
 return <><div className="admin-title"><div><span className="eyebrow">SOURCE QUESTION FACTORY</span><h1>Source → Knowledge → Existing Factory</h1><p>TXT/Markdown pilot with human knowledge approval and the existing factory review gate.</p></div></div>{message&&<div className="admin-alert">{message}</div>}
 <section className="factory-layout"><div className="admin-panel factory-form"><h2>Import source</h2><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Extracted text preview<textarea rows={10} value={content} onChange={e=>setContent(e.target.value)}/></label><button className="primary" disabled={busy} onClick={()=>act(async()=>{const r=await adminApi.createSource({title,sourceType:'text',content});setDetail({source:r.source,chunks:[],knowledgeUnits:[],plans:[],provenance:[]})})}>Confirm import</button></div><div className="admin-panel"><h2>Source Library</h2><div className="job-list">{sources.map(s=><button key={s.id} onClick={()=>act(()=>adminApi.source(s.id),s.id)}><span><b>{s.title}</b><small>{s.sourceType} · {s.createdAt}</small></span><span className="badge">{s.status}</span></button>)}</div></div></section>
 {detail&&<section className="admin-panel"><div className="panel-head"><div><h2>{detail.source.title}</h2><small className="mono">{detail.source.id}</small></div><div><button className="secondary" disabled={busy} onClick={()=>act(()=>adminApi.chunkSource(detail.source.id))}>1. Chunk</button> <button className="secondary" disabled={busy||!detail.chunks.length} onClick={()=>act(()=>adminApi.extractSource(detail.source.id))}>2. Extract</button></div></div><p>Chunks: {detail.chunks.length} · Knowledge: {detail.knowledgeUnits.length} · Plans: {detail.plans.length} · Candidates: {detail.provenance.length}</p><div className="factory-candidates">{detail.knowledgeUnits.map(u=><article className="factory-candidate" key={u.id}><div className="candidate-top"><b>{u.topic}</b><span className="badge">{u.status}</span></div><p>{u.canDo}</p><small>{u.level} · confidence {Math.round(u.confidence*100)}%</small>{u.status==='review'&&<button className="secondary" disabled={busy} onClick={()=>act(()=>adminApi.approveKnowledge(u.id))}>Approve knowledge</button>}</article>)}</div>{detail.knowledgeUnits.some(x=>x.status==='approved')&&<div><input type="number" min={1} max={30} value={count} onChange={e=>setCount(Number(e.target.value))}/> <button className="primary" disabled={busy} onClick={()=>act(()=>adminApi.planSource(detail.source.id,count))}>3. Generate plan</button></div>}{detail.plans.map(p=><article className="factory-candidate" key={p.id}><b>Plan: {p.items.length} items</b><p>{p.items.map(x=>x.section).join(' · ')}</p><button className="primary" disabled={busy||p.status==='generated'} onClick={()=>act(()=>adminApi.generatePlan(p.id))}>4. Generate via Existing Factory</button></article>)}</section>}</>
}
