'use client';
import { useEffect,useState } from 'react';
import { adminApi } from '@/lib/api-client';
import { ADMIN_STATUS_LABELS } from '@/lib/admin-ui';
import type { KnowledgeUnit,QuestionPlan,QuestionProvenance,SourceChunk,SourceDocument } from '@/lib/server/source-domain';

type Detail={source:SourceDocument;chunks:SourceChunk[];knowledgeUnits:KnowledgeUnit[];plans:QuestionPlan[];provenance:QuestionProvenance[]};
const sourceStatus:Record<string,string>={draft:'Bản nháp',parsed:'Đã phân tích',chunked:'Đã chia đoạn',extracting:'Đang trích xuất',review:'Chờ duyệt',ready:'Sẵn sàng',failed:'Thất bại',approved:'Đã duyệt',rejected:'Đã từ chối'};
const knowledgeStatus=(status:string)=>sourceStatus[status]??(status in ADMIN_STATUS_LABELS?ADMIN_STATUS_LABELS[status as keyof typeof ADMIN_STATUS_LABELS]:status);

export default function SourcesClient(){
  const [sources,setSources]=useState<SourceDocument[]>([]),[detail,setDetail]=useState<Detail|null>(null),[title,setTitle]=useState('Thử nghiệm tiếp nhận tại bệnh viện'),[content,setContent]=useState('病院で受付をします。\n\n受付で保険証を出します。\n\nどこが痛いか簡単に説明します。\n\n診察が終わったら会計をします。'),[count,setCount]=useState(4),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const load=async(id?:string)=>{const result=await adminApi.sources();setSources(result.sources);if(id)setDetail(await adminApi.source(id))};
  useEffect(()=>{void load().catch(show)},[]);
  function show(error:unknown){setMessage(error instanceof Error?error.message:String(error))}
  async function act(action:()=>Promise<unknown>,id?:string){setBusy(true);setMessage('');try{await action();await load(id||detail?.source.id)}catch(error){show(error)}finally{setBusy(false)}}
  return <>
    <div className="admin-title"><div><span className="eyebrow">XƯỞNG CÂU HỎI THEO NGUỒN</span><h1>Nguồn → Kiến thức → Xưởng câu hỏi</h1><p>Quy trình TXT/Markdown có bước duyệt kiến thức thủ công và dùng lại hệ thống QA hiện có.</p></div></div>{message&&<div className="admin-alert">{message}</div>}
    <section className="factory-layout"><div className="admin-panel factory-form"><h2>Nhập nguồn tài liệu</h2><label>Tiêu đề<input value={title} onChange={event=>setTitle(event.target.value)}/></label><label>Xem trước văn bản đã trích xuất<textarea rows={10} value={content} onChange={event=>setContent(event.target.value)}/></label><button className="primary" disabled={busy} onClick={()=>act(async()=>{const result=await adminApi.createSource({title,sourceType:'text',content});setDetail({source:result.source,chunks:[],knowledgeUnits:[],plans:[],provenance:[]})})}>Xác nhận nhập</button></div><div className="admin-panel"><h2>Thư viện nguồn</h2><div className="job-list">{sources.map(source=><button key={source.id} onClick={()=>act(()=>adminApi.source(source.id),source.id)}><span><b>{source.title}</b><small>{source.sourceType} · {new Date(source.createdAt).toLocaleString('vi-VN')}</small></span><span className="badge">{knowledgeStatus(source.status)}</span></button>)}</div></div></section>
    {detail&&<section className="admin-panel"><div className="panel-head"><div><h2>{detail.source.title}</h2><small className="mono">{detail.source.id}</small></div><div><button className="secondary" disabled={busy} onClick={()=>act(()=>adminApi.chunkSource(detail.source.id))}>1. Chia đoạn</button> <button className="secondary" disabled={busy||!detail.chunks.length} onClick={()=>act(()=>adminApi.extractSource(detail.source.id))}>2. Trích xuất</button></div></div><p>Đoạn: {detail.chunks.length} · Đơn vị kiến thức: {detail.knowledgeUnits.length} · Kế hoạch: {detail.plans.length} · Câu đã tạo: {detail.provenance.length}</p><div className="factory-candidates">{detail.knowledgeUnits.map(unit=><article className="factory-candidate" key={unit.id}><div className="candidate-top"><b>{unit.topic}</b><span className="badge">{knowledgeStatus(unit.status)}</span></div><p>{unit.canDo}</p><small>{unit.level} · độ tin cậy {Math.round(unit.confidence*100)}%</small>{unit.status==='review'&&<button className="secondary" disabled={busy} onClick={()=>act(()=>adminApi.approveKnowledge(unit.id))}>Duyệt kiến thức</button>}</article>)}</div>{detail.knowledgeUnits.some(unit=>unit.status==='approved')&&<div><input aria-label="Số câu cần lập kế hoạch" type="number" min={1} max={30} value={count} onChange={event=>setCount(Number(event.target.value))}/> <button className="primary" disabled={busy} onClick={()=>act(()=>adminApi.planSource(detail.source.id,count))}>3. Tạo kế hoạch</button></div>}{detail.plans.map(plan=><article className="factory-candidate" key={plan.id}><b>Kế hoạch: {plan.items.length} mục</b><p>{plan.items.map(item=>item.section).join(' · ')}</p><button className="primary" disabled={busy||plan.status==='generated'} onClick={()=>act(()=>adminApi.generatePlan(plan.id))}>4. Sinh qua Xưởng câu hỏi</button></article>)}</section>}
  </>;
}
