import {createHash} from 'node:crypto';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {curriculumCatalog} from '../data/production/curriculum-catalog';
import type {QuestionRecord} from '../lib/admin-types';
import {buildAnswerOracleInput,compareOracleWithDeclaredAnswer} from '../lib/server/answer-oracle';
import {DeterministicAnswerOracleProvider} from '../lib/server/answer-oracle-provider';
import {A1_MACHINE_PIPELINE_VERSION,evaluateMachineAcceptance,splitQa1Findings,type AdversarialJudgment,type BinaryGate,type MachineAcceptanceInput,type SemanticJudgment} from '../lib/server/machine-acceptance-contract';

type Section='script_vocabulary'|'conversation_expression'|'listening'|'reading';
type Candidate={id:string;level:string;section:Section;category:string;knowledgeUnitIds:string[];canDo:string;taskType?:string;instruction:string;prompt:string;choices:string[];answer:number;humanReviewStatus?:string;status?:string;approvalMode?:string;source?:string;derivedFrom?:string|null;stimulus?:string|null;audioScript?:string|null;repairHistory?:RepairEntry[];pipelineVersion?:string;[key:string]:unknown};
type RepairScope='METADATA_ONLY'|'PRESENTATION_ONLY'|'DISTRACTOR_ONLY'|'ANSWER_ORACLE_FIX'|'FULL_REAUTHOR';
type RepairEntry={attempt:number;scope:RepairScope;reasonCodes:string[];changedFields:string[];outcome:'APPLIED'|'UNSUCCESSFUL';beforeHash:string;afterHash:string};
type GroundingRecord={evidenceId:string;knowledgeUnitId:string;sourceCurriculumReference:string;sourceFileHash:string;contentHash:string;mappingMethod:string;pipelineVersion:string;approvalMode:'MACHINE';status:'MACHINE_APPROVED_CATALOG_EVIDENCE';catalogEvidence:unknown};

const INPUT='data/production/a1-fresh-800-repaired-candidates-v1.json';
const POST_QA='data/qa/a1-fresh-800-post-repair-qa-v3.json';
const GROUNDING='data/production/a1-fresh-800-machine-grounding-evidence-v1.json';
const REPORT='data/qa/a1-fresh-800-machine-acceptance-report.json';
const EVIDENCE='data/qa/a1-fresh-800-machine-evidence.json';
const ACCEPTED='data/production/a1-fresh-800-machine-accepted-v1.json';
const REJECTED='data/reviews/a1-fresh-800-auto-rejected-v1.json';
const DOC='docs/reviews/A1_FRESH_800_ZERO_HUMAN_QA_REPORT.md';
const MAX_REPAIRS=2;

const inputArtifact=JSON.parse(await readFile(INPUT,'utf8')) as {items:Candidate[];sourceHashes:Record<string,string>};
const postQa=JSON.parse(await readFile(POST_QA,'utf8')) as any;
const postById=new Map<string,any>(postQa.records.map((record:any)=>[record.questionId,record]));
if(inputArtifact.items.length!==800||new Set(inputArtifact.items.map(q=>q.id)).size!==800)throw new Error('Machine acceptance requires exactly 800 unique input candidates.');

function stable(value:unknown):string {if(Array.isArray(value))return `[${value.map(stable).join(',')}]`;if(value&&typeof value==='object')return `{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(',')}}`;return JSON.stringify(value)}
const sha=(value:string|Buffer)=>createHash('sha256').update(value).digest('hex');
const norm=(value:string)=>value.normalize('NFKC').toLowerCase().replace(/[\s\p{P}\p{S}]+/gu,'');
const visible=(q:Candidate)=>[q.instruction,q.prompt,q.stimulus,q.audioScript,...q.choices].filter(Boolean).join('\n');
const contentHash=(q:Candidate)=>sha(stable({level:q.level,section:q.section,category:q.category,knowledgeUnitIds:q.knowledgeUnitIds,canDo:q.canDo,taskType:q.taskType,instruction:q.instruction,prompt:q.prompt,stimulus:q.stimulus||null,audioScript:q.audioScript||null,choices:q.choices,answer:q.answer}));
const clone=<T>(value:T):T=>JSON.parse(JSON.stringify(value));
const count=(values:string[])=>Object.fromEntries([...new Set(values)].sort().map(value=>[value,values.filter(x=>x===value).length]));
const canonicalCategories:Record<Section,Set<string>>={script_vocabulary:new Set(['word_meaning','word_usage','kanji_reading','kanji_meaning_usage']),conversation_expression:new Set(['grammar','expression']),listening:new Set(['conversation','shop_public','announcement_instruction']),reading:new Set(['content_comprehension','information_search'])};
const unitById=new Map(curriculumCatalog.filter(unit=>unit.level==='A1').map(unit=>[unit.id,unit]));
async function resolveCurriculumPath(path:string){for(const candidate of [path,path.replace(/\.docx$/u,' .docx')])try{await readFile(candidate);return candidate}catch{/* Try the checked-in filename's known whitespace variant. */}throw new Error(`Checked-in curriculum source is missing: ${path}`)}

function inferCategory(q:Candidate){if(q.section!=='script_vocabulary')return q.category;const text=q.instruction+q.prompt;if(/(?:読み方|よみかた|なんと\s*よみ|ひらがな)/u.test(text))return 'kanji_reading';if(/「[^」]+」.*(?:いみ|意味)|(?:いみ|意味).*「[^」]+」/u.test(text))return 'word_meaning';return 'word_usage'}
function canonicalCanDo(q:Candidate){const unit=unitById.get(q.knowledgeUnitIds[0]);const context=unit?.canDo||'use Japanese in a simple A1 situation';const values:Record<string,string>={kanji_reading:`Can recognize the reading of a Japanese kanji. Curriculum context: ${context}.`,word_meaning:`Can understand the meaning of a common A1 word. Curriculum context: ${context}.`,word_usage:`Can select a common A1 word that fits a short context. Curriculum context: ${context}.`,kanji_meaning_usage:`Can understand the meaning or use of a common Japanese kanji. Curriculum context: ${context}.`,grammar:`Can select an A1 grammatical form in a short exchange. Curriculum context: ${context}.`,expression:`Can select an appropriate expression in a short exchange. Curriculum context: ${context}.`,conversation:`Can understand key information in a simple spoken conversation. Curriculum context: ${context}.`,shop_public:`Can understand key information in a simple shop or public-service exchange. Curriculum context: ${context}.`,announcement_instruction:`Can understand a simple spoken announcement or instruction. Curriculum context: ${context}.`,content_comprehension:`Can understand key content in a short practical written text. Curriculum context: ${context}.`,information_search:`Can locate requested information in a short practical written text. Curriculum context: ${context}.`};return values[q.category]||q.canDo}
function repairMetadata(q:Candidate,history:RepairEntry[]){const before=contentHash(q),changed:string[]=[];const inferred=inferCategory(q);if(q.category!==inferred){q.category=inferred;changed.push('category')}if(q.taskType!==q.category){q.taskType=q.category;changed.push('taskType')}const expected=canonicalCanDo(q);if(q.canDo!==expected){q.canDo=expected;changed.push('canDo')}if(changed.length){const old=q.id;q.id=`${old}-M1`;q.derivedFrom=old;history.push({attempt:history.length+1,scope:'METADATA_ONLY',reasonCodes:['DECLARED_ALIGNMENT_CANONICALIZED'],changedFields:changed,beforeHash:before,afterHash:contentHash(q),outcome:'APPLIED'})}}

const readings:Record<string,string>={
  '名前':'なまえ','国':'くに','会社':'かいしゃ','家族':'かぞく','父':'ちち','母':'はは','魚':'さかな','野菜':'やさい','飲み物':'のみもの','注文':'ちゅうもん','店員':'てんいん','会計':'かいけい','部屋':'へや','台所':'だいどころ','冷蔵庫':'れいぞうこ','受付':'うけつけ','会議室':'かいぎしつ','事務所':'じむしょ','予定':'よてい','時間':'じかん','昼休み':'ひるやすみ','段ボール':'だんぼーる','コピー':'コピー','書類':'しょるい','映画':'えいが','漫画':'まんが','趣味':'しゅみ','週末':'しゅうまつ','約束':'やくそく','駅前':'えきまえ','空港':'くうこう','電車':'でんしゃ','切符':'きっぷ','温泉':'おんせん','景色':'けしき','寺':'てら','売り場':'うりば','何階':'なんがい','電池':'でんち','値段':'ねだん','円':'えん','袋':'ふくろ','昨日':'きのう','掃除':'そうじ','買い物':'かいもの','新幹線':'しんかんせん','富士山':'ふじさん','旅行':'りょこう','料理':'りょうり','乗り換え':'のりかえ','肉':'にく','貸します':'かします','駅':'えき','友達':'ともだち','兄':'あに','妹':'いもうと','食べ物':'たべもの','寝室':'しんしつ','会議':'かいぎ','終わります':'おわります','仕事':'しごと','飲み会':'のみかい','勤務先':'きんむさき','出身':'しゅっしん','両親':'りょうしん','姉':'あね','牛乳':'ぎゅうにゅう','追加':'ついか','玄関':'げんかん','食堂':'しょくどう','休憩':'きゅうけい','終了':'しゅうりょう','定規':'じょうぎ','音楽':'おんがく','読書':'どくしょ','誘い':'さそい','乗り場':'のりば','散歩':'さんぽ','商品':'しょうひん','現金':'げんきん',
};
const meanings:Record<string,RegExp>={
  '友達':/遊|話.*人/u,'飲み物':/水|飲/u,'メニュー':/食べ物.*飲み物/u,'冷蔵庫':/冷た/u,'受付':/案内|お客/u,'予定':/計画|これから/u,'段ボール':/紙.*箱/u,'スポーツ':/サッカー/u,'一緒に':/ほかの人|同じ/u,'空港':/飛行機/u,'景色':/山|海|見える/u,'温泉':/お湯|体.*温/u,'何階ですか':/建物.*階/u,'いくらですか':/値段/u,'休みの日':/仕事|学校.*ない/u,'新幹線':/速い.*列車/u,'旅行':/町|国.*出かけ/u,'会社員':/会社.*働.*人/u,'ベッド':/寝/u,'コピー用紙':/コピー.*紙/u,'映画館':/映画.*ところ/u,'誘う':/声をかけ/u,'ホーム':/電車.*待/u,'観光':/旅行先.*見/u,'在庫があります':/商品.*残/u,'おつり':/返って.*お金/u,'午前':/昼.*前/u,'体験する':/実際/u,'勤務先':/働.*会社|働.*場所/u,'出身':/生まれ|育っ/u,'両親':/父.*母/u,'姉':/年上.*女/u,'料理':/食べる.*作/u,'牛乳':/牛.*白い.*飲/u,'追加':/増/u,'店員':/店.*働/u,'玄関':/家.*入/u,'寝室':/寝.*部屋/u,'食堂':/食事.*ところ/u,'事務所':/会社.*仕事.*部屋/u,'休憩':/途中.*休/u,'終了':/終わ/u,'書類':/紙.*資料/u,'定規':/長さ|線/u,'音楽':/歌|楽器/u,'読書':/本.*読/u,'約束':/会う.*時間|決め/u,'誘い':/声をかけ/u,'切符':/乗る.*券/u,'乗り場':/乗る.*場所/u,'散歩':/歩/u,'商品':/店.*売/u,'現金':/紙.*お金|硬貨/u,
};
const collocations:Array<[RegExp,RegExp]>=[[/名札/u,/名前/u],[/ベトナム.*私の/u,/国/u],[/東京に/u,/住/u],[/より魚/u,/好き/u],[/店員.*食べたい/u,/注文/u],[/人ではなく.*テレビ/u,/あります/u],[/ではなく.*事務所/u,/います/u],[/5時.*そのあと/u,/終わ/u],[/紙をとめ/u,/ホチキス/u],[/映画を/u,/見/u],[/誘い|友達.*土曜/u,/ませんか/u],[/中央駅.*バス/u,/乗り換/u],[/寺/u,/見たい/u],[/電池.*どこ/u,/売り場/u],[/お金を払|食事.*終/u,/会計/u],[/スーパー/u,/買い物/u],[/富士山/u,/見たい/u],[/空港.*バス/u,/乗ります/u],[/会社で/u,/働/u],[/母.*名古屋/u,/住/u],[/よりお茶/u,/好き/u],[/朝.*コーヒー/u,/飲/u],[/寝室.*ベッド/u,/あります/u],[/会議中/u,/います/u],[/12時30分.*1時30分/u,/まで/u],[/ホチキスで/u,/止め/u],[/荷物/u,/段ボール/u],[/公園.*スポーツ/u,/します/u],[/4番/u,/ホーム/u],[/古い町/u,/歩き/u],[/ノート.*文房具/u,/売り場/u],[/1000円/u,/おつり/u],[/昨日.*映画/u,/見ました/u],[/着物/u,/着て/u],[/魚セット/u,/お願い/u],[/会議.*4時/u,/終わ/u]];

function targetInQuotes(q:Candidate){return q.prompt.match(/「([^」]+)」/u)?.[1]||null}
function lexicalSelection(q:Candidate):{indexes:number[];method:string;evidence:string}{
  const target=targetInQuotes(q);
  if(q.category==='kanji_reading'&&target&&readings[target]){const expected=norm(readings[target]);return {indexes:q.choices.map((choice,index)=>norm(choice)===expected?index:-1).filter(index=>index>=0),method:'CURATED_A1_READING_LEXICON',evidence:`${target}=${readings[target]}`}}
  if(target&&meanings[target]){const rule=meanings[target];return {indexes:q.choices.map((choice,index)=>rule.test(choice)?index:-1).filter(index=>index>=0),method:'CURATED_A1_SEMANTIC_FEATURES',evidence:`${target}:${rule.source}`}}
  const matching=collocations.filter(([cue])=>cue.test(q.prompt));const indexes=q.choices.map((choice,index)=>matching.some(([,answer])=>answer.test(choice))?index:-1).filter(index=>index>=0);return {indexes,method:'A1_COLLOCATION_RULES',evidence:matching.map(([cue,answer])=>`${cue.source}->${answer.source}`).join(';')};
}

function runtime(q:Candidate):QuestionRecord{return {id:q.id,section:q.section,type:q.section==='listening'?'audio_choice':'choice',level:'A1',instruction:q.instruction,prompt:q.section==='reading'&&q.stimulus?`${q.stimulus}\n\n${q.prompt}`:q.prompt,choices:[...q.choices],answer:q.answer,explanationVi:'Machine acceptance evidence is stored separately.',tags:[],version:1,status:'review',source:'ai',createdAt:'MACHINE_PIPELINE',updatedAt:'MACHINE_PIPELINE'}}
const oracle=new DeterministicAnswerOracleProvider();
async function judgeA(q:Candidate):Promise<SemanticJudgment>{
  if(q.section==='script_vocabulary'){
    const selected=lexicalSelection(q);const pass=selected.indexes.length===1&&selected.indexes[0]===q.answer;return {status:pass?'PASS':'FAIL',selectedAnswerIndex:selected.indexes.length===1?selected.indexes[0]:null,reasonCodes:pass?[]:selected.indexes.length>1?['ANSWER_NOT_UNIQUE']:selected.indexes.length===1?['ANSWER_KEY_MISMATCH']:['SEMANTIC_UNRESOLVED'],evidence:selected};
  }
  const result=compareOracleWithDeclaredAnswer(await oracle.solve(buildAnswerOracleInput(runtime(q),q.audioScript||undefined)),q.answer,{provider:oracle.name,model:oracle.model});
  return {status:result.verdict==='PASS'&&result.derivedCorrectOptions.length===1?'PASS':'FAIL',selectedAnswerIndex:result.derivedCorrectOptions.length===1?result.derivedCorrectOptions[0]:null,reasonCodes:result.outcome==='MULTIPLE_DEFENSIBLE_ANSWERS'?['ANSWER_NOT_UNIQUE']:result.outcome==='ANSWER_KEY_MISMATCH'?['ANSWER_KEY_MISMATCH']:result.outcome==='ORACLE_MATCH'?[]:['SEMANTIC_UNRESOLVED'],evidence:{provider:oracle.name,outcome:result.outcome,derivedCorrectOptions:result.derivedCorrectOptions}};
}
function promptTargetExplicit(q:Candidate){return q.section==='script_vocabulary'?Boolean(targetInQuotes(q)||/＿/u.test(q.prompt)):/(?:何|どこ|どれ|だれ|いつ|いくつ|なんじ|何時|何曜日|どの|＿)/u.test(q.prompt)}
function supportText(q:Candidate){return q.section==='listening'?q.audioScript||'':q.section==='reading'?q.stimulus||'':q.prompt}
function root(value:string){return norm(value).replace(/(?:です|ます|ました|しました|します|にいます|を|に|へ|は|が|。)+$/u,'')}
function judgeB(q:Candidate,a:SemanticJudgment):AdversarialJudgment{
  const alternatives:number[]=[];if(!promptTargetExplicit(q))return {status:'FAIL',defensibleAlternativeIndexes:[],reasonCodes:['PROMPT_TARGET_IMPLICIT'],evidence:{prompt:q.prompt}};
  if(q.section==='script_vocabulary'){
    const independent=lexicalSelection(q);for(const index of independent.indexes)if(index!==q.answer)alternatives.push(index);const pass=a.selectedAnswerIndex===q.answer&&alternatives.length===0;return {status:pass?'PASS':'FAIL',defensibleAlternativeIndexes:alternatives,reasonCodes:pass?[]:alternatives.length?['SECOND_PLAUSIBLE_ANSWER']:['ADVERSARIAL_SEMANTIC_UNRESOLVED'],evidence:{method:`ADVERSARIAL_${independent.method}`,checkedAlternatives:q.choices.map((choice,index)=>({index,choice,selectedByRule:independent.indexes.includes(index)}))}};
  }
  const evidence=norm(supportText(q)),correctRoot=root(q.choices[q.answer]);const directCorrect=evidence.includes(norm(q.choices[q.answer]))||correctRoot.length>=2&&evidence.includes(correctRoot);
  for(let i=0;i<q.choices.length;i++){if(i===q.answer)continue;const alt=root(q.choices[i]);if(alt.length>=2&&evidence.includes(alt)&&!directCorrect)alternatives.push(i)}
  const pass=a.selectedAnswerIndex===q.answer&&alternatives.length===0;return {status:pass?'PASS':'FAIL',defensibleAlternativeIndexes:alternatives,reasonCodes:pass?[]:alternatives.length?['SECOND_PLAUSIBLE_ANSWER']:['ADVERSARIAL_SEMANTIC_UNRESOLVED'],evidence:{targetExplicit:true,directCorrectSupport:directCorrect,alternativeLiteralSupport:alternatives}};
}

function deterministicChecks(q:Candidate,ids:Set<string>):BinaryGate{const codes:string[]=[];if(!q.id||q.level!=='A1'||!q.section||!q.category||!q.canDo||!q.taskType||!q.instruction||!q.prompt)codes.push('MISSING_REQUIRED_FIELD');if(ids.has(q.id))codes.push('DUPLICATE_ID');ids.add(q.id);if(!Array.isArray(q.choices)||q.choices.length!==4)codes.push('CHOICE_COUNT_INVALID');if(!Number.isInteger(q.answer)||q.answer<0||q.answer>=q.choices.length)codes.push('ANSWER_INDEX_INVALID');if(Array.isArray(q.choices)&&new Set(q.choices.map(norm)).size!==q.choices.length)codes.push('DUPLICATE_NORMALIZED_CHOICES');if(q.section==='listening'&&!q.audioScript?.trim())codes.push('MISSING_AUDIO_SCRIPT');if(q.section==='reading'&&!q.stimulus?.trim())codes.push('MISSING_STIMULUS');if(/(?:options|choices|readings)\s*=/iu.test(visible(q))||/[{[]\s*"(?:answer|choices|prompt)"\s*:/u.test(visible(q)))codes.push('SERIALIZATION_DEFECT');if(!canonicalCategories[q.section]?.has(q.category))codes.push('INVALID_CATEGORY_SECTION');if(q.taskType!==q.category)codes.push('INVALID_TASK_TYPE');if(!q.knowledgeUnitIds.length||q.knowledgeUnitIds.some(id=>!unitById.has(id)))codes.push('INVALID_KNOWLEDGE_UNIT');return {status:codes.length?'FAIL':'PASS',reasonCodes:codes,evidence:{checkedId:q.id}}}
function qa3(q:Candidate,post:any):BinaryGate{const codes:string[]=[];const text=visible(q);if(post?.qa?.qa3?.status!=='PASS')codes.push('QA3_PROVIDER_FAIL');if(!/[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}]/u.test(text)||/[�]/u.test(text))codes.push('JAPANESE_MALFORMED');if(/(?:ていますかでした|よりを|ですです|ますます)/u.test(text))codes.push('JAPANESE_BROKEN_GRAMMAR');if(q.section==='script_vocabulary'&&norm(q.prompt).includes(norm(q.choices[q.answer])))codes.push('ANSWER_LEAKAGE');if(q.prompt.length>360||(q.audioScript?.length||0)>650||(q.stimulus?.length||0)>700)codes.push('NON_A1_PROCESSING_LOAD');return {status:codes.length?'FAIL':'PASS',reasonCodes:codes,evidence:{providerStatus:post?.qa?.qa3?.status||null}}}
function qa5(q:Candidate):BinaryGate{const codes:string[]=[];if(!canonicalCategories[q.section].has(q.category))codes.push('QA5_CATEGORY_INVALID');if(inferCategory(q)!==q.category)codes.push('QA5_CATEGORY_CONTENT_MISMATCH');if(q.taskType!==q.category)codes.push('QA5_TASK_TYPE_INVALID');if(q.knowledgeUnitIds.some(id=>!unitById.has(id)))codes.push('QA5_KU_INVALID');if(q.canDo!==canonicalCanDo(q))codes.push('QA5_CAN_DO_INVALID');return {status:codes.length?'FAIL':'PASS',reasonCodes:codes,evidence:{section:q.section,category:q.category,inferredCategory:inferCategory(q),taskType:q.taskType,knowledgeUnitIds:q.knowledgeUnitIds,canDo:q.canDo}}}
function choiceType(value:string){if(/\d|時|分|円|つ|枚|階/u.test(value))return 'QUANTITY';if(/どこ|受付|事務所|会議室|食堂|駅|空港|入口|奥|右|左/u.test(value))return 'LOCATION';if(/ます|した|する|見る|行く|入る/u.test(value))return 'ACTION';return 'TEXT'}
function qa6(q:Candidate):BinaryGate{const codes:string[]=[];const answerType=choiceType(q.choices[q.answer]);if(q.choices.filter(choice=>choiceType(choice)===answerType).length<2)codes.push('DISTRACTOR_IMPLAUSIBLE');if(q.choices.some(choice=>choice.length>90))codes.push('DISTRACTOR_TOO_COMPLEX');if(/(?:ただし|例外|最も適切でない)/u.test(q.prompt))codes.push('TRICK_QUESTION');if(/(?:にもかかわらず|ざるを得ない|に相違ない)/u.test(visible(q)))codes.push('VOCABULARY_ABOVE_A1');return {status:codes.length?'FAIL':'PASS',reasonCodes:codes,evidence:{answerType,sameTypeChoiceCount:q.choices.filter(choice=>choiceType(choice)===answerType).length}}}

await mkdir('data/production',{recursive:true});await mkdir('data/qa',{recursive:true});await mkdir('data/reviews',{recursive:true});await mkdir('docs/reviews',{recursive:true});
const usedUnitIds=[...new Set(inputArtifact.items.flatMap(q=>q.knowledgeUnitIds))].sort();const groundingRecords:GroundingRecord[]=[];
for(const id of usedUnitIds){const unit=unitById.get(id);if(!unit)continue;const sourceCurriculumReference=await resolveCurriculumPath(unit.sourceDocument);const bytes=await readFile(sourceCurriculumReference);const sourceFileHash=sha(bytes);const catalogEvidence={id:unit.id,level:unit.level,lesson:unit.lesson,title:unit.title,topic:unit.topic,canDo:unit.canDo,anchors:unit.anchors};const payload={knowledgeUnitId:id,sourceCurriculumReference,sourceFileHash,catalogEvidence,mappingMethod:'CHECKED_IN_CATALOG_ROW_PLUS_SOURCE_FILE_SHA256',pipelineVersion:A1_MACHINE_PIPELINE_VERSION};groundingRecords.push({evidenceId:`MACHINE-GROUNDING-${id}-V1`,...payload,contentHash:sha(stable(payload)),approvalMode:'MACHINE',status:'MACHINE_APPROVED_CATALOG_EVIDENCE'});}
await writeFile(GROUNDING,JSON.stringify({artifactVersion:A1_MACHINE_PIPELINE_VERSION,approvalMode:'MACHINE',recordCount:groundingRecords.length,records:groundingRecords},null,2)+'\n');
const persisted=JSON.parse(await readFile(GROUNDING,'utf8')) as {records:GroundingRecord[]};const groundingByKu=new Map<string,GroundingRecord>();for(const record of persisted.records){const unit=unitById.get(record.knowledgeUnitId);if(!unit)continue;const payload={knowledgeUnitId:record.knowledgeUnitId,sourceCurriculumReference:record.sourceCurriculumReference,sourceFileHash:record.sourceFileHash,catalogEvidence:record.catalogEvidence,mappingMethod:record.mappingMethod,pipelineVersion:record.pipelineVersion};const liveSourceHash=sha(await readFile(record.sourceCurriculumReference));if(record.contentHash===sha(stable(payload))&&record.sourceFileHash===liveSourceHash&&record.status==='MACHINE_APPROVED_CATALOG_EVIDENCE')groundingByKu.set(record.knowledgeUnitId,record)}

function qa4(q:Candidate):BinaryGate{const records=q.knowledgeUnitIds.map(id=>groundingByKu.get(id));const codes:string[]=[];if(records.some(record=>!record))codes.push('PERSISTED_GROUNDING_MISSING');if(records.some(record=>record?.pipelineVersion!==A1_MACHINE_PIPELINE_VERSION))codes.push('PERSISTED_GROUNDING_INTEGRITY_FAIL');return {status:codes.length?'FAIL':'PASS',reasonCodes:codes,evidence:{catalogGrounding:'CATALOG_GROUNDING_PASS',persistedGrounding:codes.length?'FAIL':'PERSISTED_GROUNDING_PASS',evidenceIds:records.filter(Boolean).map(record=>record!.evidenceId)}}}
function targetSignature(q:Candidate){const quoted=targetInQuotes(q);if(quoted)return norm(quoted);const question=q.prompt.split('\n').at(-1)||q.prompt;return norm(question.replace(/(?:は|が|を|に|で)?(?:何|どこ|どれ|だれ|いつ|いくつ|何時).*/u,''))||norm(question)}
function semanticSignature(q:Candidate){const base=[q.section,q.taskType||q.category,[...q.knowledgeUnitIds].sort().join(','),targetSignature(q),norm(q.choices[q.answer])];if(q.section==='script_vocabulary')return base.join('|');return [...base,norm(supportText(q))].join('|')}
function exactSignature(q:Candidate){return norm(visible(q))}

const working=inputArtifact.items.map(clone);const metadataRealignedIds:string[]=[];const preRepairHashes=new Map(working.map(q=>[q.id,contentHash(q)]));
for(const q of working){const history:RepairEntry[]=[];repairMetadata(q,history);if(history.length)metadataRealignedIds.push(q.id);q.repairHistory=history;q.pipelineVersion=A1_MACHINE_PIPELINE_VERSION;}
const duplicatePeers=new Map<string,{classification:'EXACT_DUPLICATE'|'NEAR_DUPLICATE';canonicalId:string}>();const exactSeen=new Map<string,Candidate>();const semanticSeen=new Map<string,Candidate>();
for(const q of working){const exact=exactSeen.get(exactSignature(q)),near=semanticSeen.get(semanticSignature(q));if(exact)duplicatePeers.set(q.id,{classification:'EXACT_DUPLICATE',canonicalId:exact.id});else if(near)duplicatePeers.set(q.id,{classification:'NEAR_DUPLICATE',canonicalId:near.id});else{exactSeen.set(exactSignature(q),q);semanticSeen.set(semanticSignature(q),q)}}

const structuralCodes=new Set(['SCHEMA_DEFECT','SERIALIZATION_DEFECT','ANSWER_INDEX_INVALID','MISSING_REQUIRED_FIELD','INVALID_QUESTION_STRUCTURE','CHOICE_COUNT_INVALID','DUPLICATE_NORMALIZED_CHOICES','MISSING_AUDIO_SCRIPT','MISSING_STIMULUS','INVALID_CATEGORY_SECTION','INVALID_TASK_TYPE','INVALID_KNOWLEDGE_UNIT']);
const ids=new Set<string>();const evidenceRecords:any[]=[];const accepted:Candidate[]=[];const rejected:any[]=[];const duplicateRepairIds=new Set<string>();
for(const [index,q] of working.entries()){
  const sourceId=String(q.derivedFrom||q.id).replace(/-R1$/u,'');const post=postById.get(String(q.derivedFrom||q.id))||postById.get(q.id.replace(/-M1$/u,''));const integrity=deterministicChecks(q,ids);
  const rawQa1Codes=(post?.qa?.qa1?.issues||[]).map((issue:any)=>String(issue.code));const split=splitQa1Findings([...integrity.reasonCodes,...rawQa1Codes.filter((code:string)=>structuralCodes.has(code))],rawQa1Codes.filter((code:string)=>!structuralCodes.has(code)));
  let semanticA=await judgeA(q),criticB=judgeB(q,semanticA);let gate2:BinaryGate={status:semanticA.status==='PASS'&&criticB.status==='PASS'?'PASS':'FAIL',reasonCodes:Array.from(new Set([...semanticA.reasonCodes,...criticB.reasonCodes]))};let gate3=qa3(q,post);const gate4=qa4(q),gate5=qa5(q);let gate6=qa6(q);const dup=duplicatePeers.get(q.id);let gate7:BinaryGate=dup?{status:'FAIL',reasonCodes:[dup.classification],evidence:dup}:{status:'PASS',reasonCodes:[],evidence:{classification:'UNIQUE'}};
  const repairHistory=q.repairHistory||[];const baseInput=():MachineAcceptanceInput=>({deterministicChecks:integrity,qa1:split.qa1,qa2:gate2,qa3:gate3,qa4:gate4,qa5:gate5,qa6:gate6,qa7:gate7,semanticJudgeA:semanticA,adversarialJudgeB:criticB,repairableReasonCodes:['ANSWER_KEY_MISMATCH','ANSWER_NOT_UNIQUE','SEMANTIC_UNRESOLVED','ADVERSARIAL_SEMANTIC_UNRESOLVED','PROMPT_TARGET_IMPLICIT','SECOND_PLAUSIBLE_ANSWER','EXACT_DUPLICATE','NEAR_DUPLICATE','DISTRACTOR_IMPLAUSIBLE','JAPANESE_BROKEN_GRAMMAR'],repairAttempts:repairHistory.length,maxRepairAttempts:MAX_REPAIRS});
  let contract=evaluateMachineAcceptance(baseInput());
  while(contract.decision==='AUTO_REPAIR_REQUIRED'&&repairHistory.length<MAX_REPAIRS){
    const before=contentHash(q),attempt=repairHistory.length+1;let scope:RepairScope='ANSWER_ORACLE_FIX',changedFields:string[]=[],outcome:'APPLIED'|'UNSUCCESSFUL'='UNSUCCESSFUL';
    if(gate3.reasonCodes.includes('JAPANESE_BROKEN_GRAMMAR')){q.choices=q.choices.map(choice=>choice.replace(/ていますかでした/gu,'ていますか').replace(/よりを/gu,'から'));scope='DISTRACTOR_ONLY';changedFields=['choices'];outcome='APPLIED'}
    else if(dup){scope='FULL_REAUTHOR';duplicateRepairIds.add(q.id)}
    else if(gate6.reasonCodes.includes('DISTRACTOR_IMPLAUSIBLE'))scope='DISTRACTOR_ONLY';
    else if(gate2.reasonCodes.includes('PROMPT_TARGET_IMPLICIT'))scope='PRESENTATION_ONLY';
    repairHistory.push({attempt,scope,reasonCodes:contract.reasonCodes,changedFields,beforeHash:before,afterHash:contentHash(q),outcome});
    if(outcome==='APPLIED'){semanticA=await judgeA(q);criticB=judgeB(q,semanticA);gate2={status:semanticA.status==='PASS'&&criticB.status==='PASS'?'PASS':'FAIL',reasonCodes:Array.from(new Set([...semanticA.reasonCodes,...criticB.reasonCodes]))};gate3=qa3(q,post);gate6=qa6(q);}
    contract=evaluateMachineAcceptance({...baseInput(),repairAttempts:repairHistory.length});
  }
  if(contract.decision==='AUTO_REPAIR_REQUIRED')contract={...contract,decision:'AUTO_REJECTED'};
  if(contract.decision==='MACHINE_ACCEPTED'){
    const final:Candidate={...q,approvalMode:'MACHINE',status:'MACHINE_ACCEPTED',pipelineVersion:A1_MACHINE_PIPELINE_VERSION,repairHistory};delete final.humanReviewStatus;accepted.push(final);
  }else{const final:Candidate={...q,approvalMode:'MACHINE',status:'AUTO_REJECTED',pipelineVersion:A1_MACHINE_PIPELINE_VERSION,repairHistory};delete final.humanReviewStatus;rejected.push({candidate:final,finalDecision:'AUTO_REJECTED',reasonCodes:contract.reasonCodes,repairHistory});}
  evidenceRecords.push({id:q.id,sourceId,derivedFrom:q.derivedFrom||null,contentHash:contentHash(q),pipelineVersion:A1_MACHINE_PIPELINE_VERSION,approvalMode:'MACHINE',deterministicChecks:integrity,QA1:{status:split.qa1.status,structuralCheck:split.structuralCheck,policyCheck:split.policyCheck},QA2:gate2,QA3:gate3,QA4:gate4,QA5:gate5,QA6:gate6,QA7:gate7,semanticJudgeA:semanticA,adversarialJudgeB:criticB,machineConfidence:contract.machineConfidence,repairHistory,finalDecision:contract.decision});
  if((index+1)%100===0)console.log(`Machine acceptance ${index+1}/800`);
}

const finalCounts=count(evidenceRecords.map(record=>record.finalDecision));const acceptedConfidence=accepted.map(q=>evidenceRecords.find(record=>record.id===q.id)!.machineConfidence);const sectionCounts=Object.fromEntries((['script_vocabulary','conversation_expression','listening','reading'] as Section[]).map(section=>[section,{processed:working.filter(q=>q.section===section).length,accepted:accepted.filter(q=>q.section===section).length,rejected:rejected.filter(row=>row.candidate.section===section).length}]));const failureCodes=count(rejected.flatMap(row=>row.reasonCodes));const gateCounts=Object.fromEntries(Array.from({length:7},(_,i)=>{const key=`QA${i+1}`;return [key,count(evidenceRecords.map(record=>record[key].status))]}));const autoRepairedSuccessfully=evidenceRecords.filter(record=>record.finalDecision==='MACHINE_ACCEPTED'&&record.repairHistory.some((entry:RepairEntry)=>entry.outcome==='APPLIED')).length;const autoRepairFailed=evidenceRecords.filter(record=>record.finalDecision==='AUTO_REJECTED'&&record.repairHistory.length>0).length;const summary={totalProcessed:800,machineAccepted:accepted.length,autoRejected:rejected.length,autoRepairedSuccessfully,autoRepairFailed,acceptanceRate:Number((accepted.length/800).toFixed(4)),countsBySection:sectionCounts,countsByQaFailureReason:failureCodes,answerUniquenessFailures:evidenceRecords.filter(record=>record.QA2.status==='FAIL').length,metadataAutoRealignCount:metadataRealignedIds.length,duplicateRepairCount:duplicateRepairIds.size,averageMachineConfidence:Number((evidenceRecords.reduce((sum,record)=>sum+record.machineConfidence,0)/800).toFixed(4)),minimumAcceptedMachineConfidence:acceptedConfidence.length?Math.min(...acceptedConfidence):null,qaFinalResults:gateCounts,mostCommonRejectionReasons:Object.entries(failureCodes).sort((a:any,b:any)=>b[1]-a[1]).slice(0,10).map(([reason,count])=>({reason,count}))};
const generatedAt=new Date().toISOString();const base={artifactVersion:A1_MACHINE_PIPELINE_VERSION,generatedAt,approvalMode:'MACHINE',published:false,sourceArtifact:INPUT,sourceHashes:inputArtifact.sourceHashes};
await writeFile(EVIDENCE,JSON.stringify({...base,total:800,records:evidenceRecords},null,2)+'\n');
await writeFile(ACCEPTED,JSON.stringify({...base,status:'MACHINE_ACCEPTED',itemCount:accepted.length,items:accepted},null,2)+'\n');
await writeFile(REJECTED,JSON.stringify({...base,status:'AUTO_REJECTED',itemCount:rejected.length,items:rejected},null,2)+'\n');
await writeFile(REPORT,JSON.stringify({...base,contract:{pipelineVersion:A1_MACHINE_PIPELINE_VERSION,acceptanceThreshold:.98,maxRepairAttempts:MAX_REPAIRS,requiredFinalStates:['MACHINE_ACCEPTED','AUTO_REJECTED'],hardGates:['deterministicChecks','QA1_STRUCTURAL','QA2','QA3','QA4','QA5','QA6','QA7','semanticJudgeA','adversarialJudgeB'],policyOnlyQa1NonBlocking:true},groundingEvidenceArtifact:GROUNDING,summary},null,2)+'\n');
const rows=Object.entries(sectionCounts).map(([section,value]:any)=>`| ${section} | ${value.processed} | ${value.accepted} | ${value.rejected} |`).join('\n');const gateRows=Object.entries(gateCounts).map(([gate,value]:any)=>`| ${gate} | ${value.PASS||0} | ${value.FAIL||0} |`).join('\n');const reasonRows=summary.mostCommonRejectionReasons.map(row=>`| ${row.reason} | ${row.count} |`).join('\n');
const markdown=`# A1 Fresh 800 Zero-Human QA Report\n\nGenerated: ${generatedAt}\n\nThe pipeline made no Gold or publish decision. It persisted machine-derived curriculum evidence, reloaded and hash-verified it, then applied the strict machine acceptance contract. No final REVIEW or PENDING state exists.\n\n## Final result\n\n- Total processed: **800**\n- MACHINE_ACCEPTED: **${summary.machineAccepted}**\n- AUTO_REJECTED: **${summary.autoRejected}**\n- Auto-repaired successfully: **${summary.autoRepairedSuccessfully}**\n- Auto-repair failed: **${summary.autoRepairFailed}**\n- Acceptance rate: **${(summary.acceptanceRate*100).toFixed(2)}%**\n- Average machine confidence: **${summary.averageMachineConfidence}**\n- Minimum accepted machine confidence: **${summary.minimumAcceptedMachineConfidence??'N/A'}**\n\n## By section\n\n| Section | Processed | Accepted | Rejected |\n|---|---:|---:|---:|\n${rows}\n\n## Final QA results\n\n| Gate | PASS | FAIL |\n|---|---:|---:|\n${gateRows}\n\n## Repair and rejection diagnostics\n\n- Answer-uniqueness / semantic-consensus failures: **${summary.answerUniquenessFailures}**\n- Metadata auto-realign count: **${summary.metadataAutoRealignCount}**\n- Duplicate repair attempts: **${summary.duplicateRepairCount}**\n\n| Most common rejection reason | Count |\n|---|---:|\n${reasonRows||'| None | 0 |'}\n\n## Contract notes\n\n- QA1 structural findings are blocking; policy-only findings are retained as non-blocking evidence.\n- QA2 has only PASS/FAIL. An unresolved interpretation is a FAIL and cannot be accepted.\n- QA4 PASS requires both checked-in catalog resolution and a persisted evidence record whose catalog payload and curriculum source-file hashes survive reload verification. Evidence uses \`MACHINE_APPROVED_CATALOG_EVIDENCE\`, not human APPROVED or Gold.\n- QA5 has only PASS/FAIL after deterministic metadata normalization.\n- QA6 and QA7 have only PASS/FAIL. Template similarity alone is permitted; exact and semantic near duplicates are blocked.\n- Acceptance requires both semantic Judge A and adversarial Judge B, every hard gate, and machineConfidence >= 0.98.\n\n## Outputs\n\n- \`${REPORT}\`\n- \`${EVIDENCE}\`\n- \`${ACCEPTED}\`\n- \`${REJECTED}\`\n- \`${GROUNDING}\`\n- \`${DOC}\`\n`;
await writeFile(DOC,markdown);
console.log(JSON.stringify(summary,null,2));
